### ISSUE TITLE
contraints for individual parameter observations

### ISSUE THREAD

**Issue by RobertMyles** [greta-dev/greta#101]
Hi,
Sorry if this is in the documentation somewhere (I couldn't find it), but I was wondering how I could go about constraining particular values of a parameter. For example, in many IRT models of legislative voting behaviour, two legislators are often constrained to help identify the model. So, if the parameter in question is theta let's say, it would be something like this (in JAGS code):
```
theta[1] ~ dnorm(-1, 1)
theta[2] ~ dnorm(1, 1)
```
And the rest of the thetas are `dnorm(0, 1)`. Is there a way to do this with the `normal()` function in greta?

**Comment by goldingn** [comment]
Hi Robert,

You sure can. `normal()` is vectorised and broadcasts the dimensions of its arguments, so you can pass it a vector of means:
```r
library(greta)
mean <- c(-1, 1, rep(0, 8))
theta <- normal(mean, 1)
```
It will expand the standard deviations out to match, or you can pass a vector there too. This also works with arrays of other dimensions:
```r
mean <- zeros(3, 3)
sd <- ones(3, 3)
mean[1:2] <- c(-1, 1)
sd[1:2] <- c(0.5, 0.5)
theta <- normal(mean, sd)
```
---

Sorry the wasn't clear from the docs. You're not the only one who has asked a question along these lines, so I obviously need to add to that helpfile. I'll add a separate issue for that now.

**Comment by RobertMyles** [comment]
Thanks Nick, that seems like it will work perfectly.
