### ISSUE TITLE
pass initial values as a named list

### ISSUE THREAD

**Issue by goldingn** [greta-dev/greta#105]
With values corresponding to greta arrays, rather than a vector of unconstrained parameters. I.e.:

```r
a = normal(0, 1, dim = 3)
b = lognormal(0, 2)
c <- a * b

m <- model(c)

init <- list(a = c(0, 0, 0), b = 3)
draws <- mcmc(m, initial_values = init)
```

**Comment by bonStats** [comment]
Is there examples available for using the `initial_values` argument as it currently stands? I can't seem to find any...

**Comment by goldingn** [comment]
I'm afraid not, but here's the gist:
At the moment, initial_values has to be a single vector, giving the parameters for all values, transformed to have full support (not constrained positive etc.) the names of those elements correspond to the internal representation of the model, not to the greta arrays created by the user, so they're basically impossible to decipher.
 
What you can do now, by hacking around, is extract an example vector and assign to that:

```r
a = normal(0, 1, dim = 3)
b = lognormal(0, 2)
c <- a * b

m <- model(c)

init <- m$dag$example_parameters()
init
```
>```r
>variable_11 variable_12 variable_13  variable_2 
>         NA          NA          NA          NA 
>```
```r
init[] <- rnorm(length(init))
draws <- mcmc(m, initial_values = init)
```

Obviously that's horrible as a user interface, and the ability to pass initial values in sensible way is important, so I'm planning to implement the functionality described above in the next release (soon!)

If you're itching to use the nicer interface, I've fleshed out the core of it (but not tested it) in [this gist](https://gist.github.com/goldingn/5edeb15082ac6e1525351c48bc31ada3) which is intended to work with my dev version of greta, that you can install with: `remotes::install_github("goldingn/greta@dev")`

After loading those functions, you could convert a list to this vector like this:

```r
inits_list <- list(a = c(0, 0, 0), b = 3)
inits <- parse_inits(inits_list, m)
draws <- mcmc(m, initial_values = inits)
```

When I implement this in greta, it won't be a separate function, you'll just be able to pass a named list (or a function that generates one) to the `initial_values` argument

**Comment by goldingn** [comment]
I've just pushed a branch `initial_values` that implements user-provided initial values on the constrained scale. You can install it with: `devtools::install_github("greta-dev/greta@initial_values")`

With that branch you can do things like:
```r
library(greta)
sd <- uniform(0, 1)
z <- normal(0, sd, dim = 3)
m <- model(z)
```
simple initial values:
```r
inits <- initials(z = rnorm(3), sd = 0.5)
draws <- mcmc(m, initial_values = inits)
```
initial values for only some of the parameters (greta initialises the rest):
```r
inits <- initials(sd = runif(1))
draws <- mcmc(m, initial_values = inits)
```
different values initialised on different chains:
```r
inits <- list(initials(z = rnorm(3)),
              initials(sd = runif(1)))
draws <- mcmc(m, chains = 2, initial_values = inits)
```
Here's a convenient syntax to semi-control the inits, but have them different for each chain:
```r
inits <- replicate(2,
                   initials(z = rnorm(3), sd = runif(1)),
                   simplify = FALSE)
draws <- mcmc(m, chains = 2, initial_values = inits)
```

Currently initial values can only be set for *variable* greta arrays, which covers most use cases, but not e.g. the output of `wishart()`, which is an operation greta array following a distribution. The variable greta array from which that is created is not returned to the user, so this currently errors:
```r
w <- wishart(3, diag(2))
m <- model(w)
inits <- initials(w = diag(2))
draws <- mcmc(m, initial_values = inits)
```
> ```
> Error: initial values can only be set for variable greta arrays 
> ```

I have plans to enable initial values to be set in that case, but may not get around to it until after the next release.

**Comment by goldingn** [comment]
The initial_values branch has now been merged into the dev branch and deleted

**Comment by vitkl** [comment]
Do you still have plans to enable initial values for operation greta arrays following a distribution?
I am specifically interested in `dirichlet()`. If I were to put something together quickly should I be replacing the c array (right) or the array that corresponds to the circle on the left?
I can try modifying the output of `prep_initials()` within `opt()` to input my initial values.
![Screen Shot 2019-07-31 at 13 25 12](https://user-images.githubusercontent.com/22567383/62211526-a8cd3d80-b396-11e9-9518-18d3948099ec.png)

**Comment by goldingn** [comment]
The plan is to fix `dirichlet()` so that instead of the current hack of placing a distribution on the operation, it's a variable like all the others. That'll be much simpler and easier to maintain than passing initials back through operations (which are not guaranteed to be [bijective](https://en.wikipedia.org/wiki/Bijection)).

There are a bunch of different multivariate variable types that would benefit from this, and we can expose those to the user as different types of variable constructor. Ie. in addition to the current `variable()`, we can have `simplex_variable()` (which we'd use for dirichlet), `correlation_matrix_variable()` and `covariance_matrix_variable()` (and others I haven't thought of yet). This will be easier to do now that TensorFlow Probability has a mature bijectors interface, including all the log Jacobian adjustments that are required.

To get a hack working for your problem, I would suggest digging the greta array for the variable (on the left) out as a greta and trying to set initials on that.  You need to set initials that are not constrained to sum to 1; that constraint will then be enforced. Here's some code which should work for you:
```r
library(greta)

alpha <- ones(1, 3)
p <- dirichlet(alpha)

# internal greta functions
get_node <- .internals$greta_arrays$get_node
as.greta_array <- .internals$greta_arrays$as.greta_array

# dig out the greta array corresponding to the unconstrained version of p
p_node <- get_node(p)
vble_node <- p_node$children[[1]]
vble <- as.greta_array(vble_node)

# now if you plot the model, the variable is now labelled as vble
m <- model(p)
plot(m)

# vble is constrained between 0 and 1, you can map from initial values for vble to initial values for p with:
vble_vals <- runif(3)
p_vals <- vble_vals / sum(vble_vals)

# check this:
calculate(p, list(vble = vble_vals))

# set initials on vble
inits <- replicate(4,
                   initials(
                     vble = t(runif(3))
                   ),
                   simplify = FALSE)

draws <- mcmc(m, initial_values = inits)
```

**Comment by vitkl** [comment]
Thanks for your very quick reply and the hack - works for me!

As for the variable constructors do you think `sparse_variable()` will be a useful one?
This is probably more relevant for sparse greta arrays for data rather than parameters (https://forum.greta-stats.org/t/sparse-matrix-format-for-count-and-binary-data-setting-dtype-of-tensors/124/6?u=vitaliikl).

**Comment by goldingn** [comment]
It's possible. Maybe a good sparse interface wouldn't require this, but instead combine a simple `variable()` with the index and dimension data. Worth thinking through.
