### ISSUE TITLE
sci py optimisers? low hanging fruit

### ISSUE THREAD

**Issue by bhattsamir** [greta-dev/greta#110]
There is a wrapper in tensorflow to allow for other optimisers like L-BFGS in R

here is an example below

optimizer = tf$contrib$opt$ScipyOptimizerInterface(train_loss, method='L-BFGS-B',options=dict(
											 'maxiter'= 200000,
											 'maxfun'= 1e6,
											 'ftol'= 1e-4,
											 'disp'=TRUE
											 ))
sess = tf$Session()
init = tf$global_variables_initializer()
sess$run(init) # initialise session

optimizer$minimize(session=sess,
			feed_dict=dict(.....))

Seems like low hanging fruit to put these into greta - I am happy to give it a try should you wish.

**Comment by goldingn** [comment]
Yeah, please do!

Adagrad is ported already, so it should be fairly straightforward to add these as alternatives methods in `greta::optim()`. I just never got around to it.

I'll be refactoring the internal code for the inference methods soon so that the syntax is like:

```r
optim(model, method = adagrad(stepsize = 0.1))
```

But I can translate all the code over then, so don't let that stop you!

**Comment by bhattsamir** [comment]
example code for scipy optimisers



tfe <- model$dag$tf_environment

with(tfe, optimizer <- tf$contrib$opt$ScipyOptimizerInterface(-joint_density, method='L-BFGS-B',options=dict('disp'=TRUE )))
with(tfe, sess$run(tf$global_variables_initializer()))
par = model$dag$trace_values()
#matrix(par[grep("Sigma",names(par))],nrow=6,ncol=6)

with(tfe, sess$run(-joint_density))
with(tfe, optimizer$minimize(session=sess))
with(tfe, sess$run(-joint_density))
par = model$dag$trace_values()

**Comment by goldingn** [comment]
There's now a branch `generalise_optimisers` for this, which enables TF or Scipy optimisers to be set up. To make this feature-complete:

 - [ ] the parameters of those optimisers need to be added to the constructors
 - [ ] other TF and SciPy constructors need to be added
 - [ ] the internals of `opt()` should use R6, and inherit from the inference class (for better checking & specification of initial values, etc.)

**Comment by goldingn** [comment]
merged into dev branch now
