### ISSUE TITLE
switch to tensorflow HMC implementation? 

### ISSUE THREAD

**Issue by goldingn** [greta-dev/greta#114]
now defined [here](https://github.com/tensorflow/tensorflow/blob/64f0ebd33a7c868da3c8f1ea15adf358c578f227/tensorflow/contrib/bayesflow/python/ops/hmc_impl.py) and worth trying out. This might add a speedup, though currently it doesn't use a mass matrix.

**Comment by goldingn** [comment]
Using tensorflow's HMC is a massive speedup, it skips some very costly R-> Python -> conversions. Like, about 100x faster for small models.

I have a working prototype, and will bring it into the dev branch ASAP.

Still no mass matrix, but the parameters can be tuned fairly easily from R by running the python version in batches.

**Comment by pteetor** [comment]
Thank you, Nick. This is an amazing development. I look forward to experimenting with HMC via _greta_.

What setting changes, if any, are needed to harness the TensorFlow HMC implemenation? Can you point me to the appropriate location within the software stack? Thank you!

**Comment by goldingn** [comment]
There's nothing implemented in greta yet. It'll takes some rejigging of internal code.
Here's a super-hacky gist that works for now though: https://gist.github.com/goldingn/79859cbdd4496f64015fb9c21244d259
It requires TensorFlow 1.5.

I'll post my progress in this issue, and let you know when this is integrated into a development version of the package.

**Comment by flyaflya** [comment]
Nick:  What is the estimated timeline for making the tensorflow-probability speedup available in a stable release?  I would like to plan to teach Greta to grad students with these performance improvements starting around October.  I kept trying a bunch of things to get the install of tensorflow-probability working and it finally worked (not sure how).  So, I hope that I can isolate my students from my installation issues.

Aside from the above, I just wanted to say thanks for Greta and the speedup.  From a teaching perspective, Greta is the easiest entry into Bayesian inference.  And as far as the speedup is concerned, I am running a very little beta-Bernoulli benchmarking model for teaching purposes and runtime went from 32 seconds to 10 seconds on my machine.  This is huge!!  I can now run models on the fly in class without fear of losing my audience.

**Comment by goldingn** [comment]
Oh, that's great to hear!

The estimated timeline to get that on the stable release is about two weeks - I just started a sprint to get that release out.

There should also be a Metropolis-Hastings sampler in the next release, which will sample even faster than HMC.

**Comment by goldingn** [comment]
Still going with that sprint. Taking longer than planned (I ended up adding a bunch more features) but should be on CRAN by the end of the month. I've made a bunch of performance improvements to sampling on the dev branch over the last week or so.

I'm tidying up issues that are resolved on dev. But please open a new issue, or bug me for a more up to date release timeline if you like!
