### ISSUE TITLE
evaluate() name conflict, or eager mode?

### ISSUE THREAD

**Issue by goldingn** [greta-dev/greta#129]
The development version of greta has a handy `evaluate()` function, to see what values a greta array would have, if the variable greta arrays on which it depends were to take a specific set of values. E.g.:

```r
library(greta)
a <- normal(0, 1)
b <- a ^ 2
evaluate(b, list(a = 3))
```
> ```
>      [,1]
> [1,]    9
> ```

Unfortunately, R tensorflow now also has an S3 generic `evaluate()`, with methods for objects in the keras and tfestimators packages. So if tensorflow or one of these packages is loaded after greta, users will get an error like:
> ```
> Error in UseMethod("evaluate") : 
>   no applicable method for 'evaluate' applied to an object of class "c('greta_array', 'array')"
> ```

To deal with this naming conflict, I can think of three options:
1. re-export tensorflow's S3 generic `evaluate()` and define a method for greta_array objects (to continue using the evaluate syntax)
2. rename `greta::evaluate()` to another verb (that doesn't conflict with functions in common R packages)
3. introduce a greta eager mode, either instead of `greta::evaluate()`, or in conjunction with option 2

**I'd really appreciate comments on what will make the most sense to users!**

---

#### 1. S3 generic

This would enable us to continue using the same `evaluate()` syntax. But using that S3 generic method would only really make sense if `greta::evaluate()`has broadly the same meaning as `keras::evaluate()` and `tfestimators::evaluate()`, such that it's obvious to users flitting between these packages* what it will do.

But `keras::evaluate()` and `tfestimators::evaluate()` both return evaluation metrics for a whole model - they don't evaluate values of intermediate nodes, conditional on earlier ones.

*I'm planning for future versions of greta to have tighter integration with tensorflow, keras etc. (to the point that you could casually embed keras deep net layers in a greta statistical model), so having an API that's broadly consistent with those is a good idea.

---

#### 2. rename

Alternative ideas for verbs:

`calculate(b, list(a  = 3))`

... and that's all I can think of. Suggestions welcome!

---

#### 3. eager mode

Somewhat like the new [TensorFlow eager mode](https://research.googleblog.com/2017/10/eager-execution-imperative-define-by.html), we could let users toggle between printing placeholder values, and printing evaluated values.

Unlike TensorFlow, greta doesn't consider variables as always having some initial set of values - they are considered to be genuinely unknown (since that fits better with how people consider statistical models). So eager mode might look something like this:

```r
library(greta)
a <- normal(0, 1)
b <- a ^ 2
b
```
> ```
> greta array (operation)
> 
>      [,1]
> [1,]  ?  
> ```
```r
# turn eager mode on, with a fixed value
considering(a = 3)
b
```
> ```
>      [,1]
> [1,]    9
> ```

```r
# turn it off
considering()
b
```
> ```
> greta array (operation)
> 
>      [,1]
> [1,]  ?  
> ```
```r
# turn it on again for another value
c <- uniform(0, 1)
d <- sqrt(c)
considering(c = 0.4)
# it has no effect on b
b
```
> ```
> greta array (operation)
> 
>      [,1]
> [1,]  ?  
> ```
```r
# but it does affect c & d
d
```
> ```
>           [,1]
> [1,] 0.6324555
> ```

This would just make use of `print.greta_array()`; so models could still be composed with eager mode on:
```r
inherits(d * 2, "greta_array")
```
> ```
> [1] TRUE
> ```

But to *use* the value, it would have to be assigned using `print` (which is nonintuitive):
```r
d_value <- print(d)
```
> ```
>           [,1]
> [1,] 0.6324555
> ```
```r
inherits(d_value * 2, "greta_array")
```
> ```
> [1] FALSE
> ```

This seems like a cool idea, but probably quite confusing to users (is `d` a greta array or an array?) So better suggests along these lines would be welcome!

**Comment by mdscheuerell** [comment]
It seems to me that option 2 would be the easiest. As you said at the top, the purpose of `evaluate()` is "to see what values a greta array would have, if the variable greta arrays on which it depends were to take a specific set of values." As the function is used to display hypotheticals and error-check, perhaps something like

`what_is(this, given_this)`.

Another idea more along the lines of the original would be `eval_array()`.

If not option 2, then I would suggest option 1. I think it would be nice to not have to turn eager mode on/off, nor worry about using `print()` for assignment.

**Comment by goldingn** [comment]
Thanks Mark, I think that's my preferred option too.

Another option is: 
```r
with(values(a = 3), b)
```

Though I'm not sure how widely `with()` is used/understood by R users

**Comment by mdscheuerell** [comment]
I like the idea of `with()`. I admit I don't use it as much as I should, but it is straightforward in its use and interpretation.

**Comment by goldingn** [comment]
OK, I'm going to go with `calculate()` because:
 - it's simple to change the existing (development) code
 - with `with()`, users will need to remember to use the `values()` wrapper function
