### ISSUE TITLE
Create a network of relationships between variables by using a system of equations

### ISSUE THREAD

**Issue by Maiae** [greta-dev/greta#131]
In greta, how can I create a network of relationships that describe how the random variables influence each other?
For example, in the following model:

   y = β0 + β1 * x1 + β2 * x2 + β3 * x3 + ε

where the variable x2 influences both the dependent variable y and the variable x1.
Can this be done by a system of equations? If so, how?

**Comment by goldingn** [comment]
I might have missed something (please let me know if I have!) but I think all you need to do is define the equation for a `x1` first, then use it in the master equation. So something like this would do it (omitting `x3` for brevity):

```r
# fake data
n <- 10
x2 <- rnorm(n)
y <- rnorm(n)

library (greta)

# parameters for x1 ~ x2
b0_x1 <- normal(0, 1)
b1_x1 <- normal(0, 1)
sigma_x1 <- normal(0, 1, truncation = c(0, Inf))

# x1 depends on x2, plus some noise
mu_x1 <- b0_x1 + b1_x1 * x2
x1 <- mu_x1 + normal(0, sigma_x1, dim = n)

# parameters for y ~ x1, x2
b0_y <- normal(0, 1)
b1_y <- normal(0, 1)
b2_y <- normal(0, 1)
sigma_y <- normal(0, 1, truncation = c(0, Inf))

# y depends on x1 and x2, plus some noise
mu <- b0_y + b1_y * x1 + b2_y * x2
distribution(y) <- normal(mu, sigma_y)
```

**Comment by goldingn** [comment]
If you're actually working with a large system of equations (lots of `x`s), then it will be more computationally efficient to express this via linear algrebra. E.g.:

```r
intercept <- rep(1, n)

# parameters for x1 ~ x2
beta_x1 <- normal(0, 1, dim = 2)
sigma_x1 <- normal(0, 1, truncation = c(0, Inf))

# x1 depends on x2, plus some noise
X_x1 <- cbind(intercept, x2)
mu_x1 <- X_x1 %*% beta_x1
x1 <- mu_x1 + normal(0, sigma_x1, dim = n)

# parameters for y ~ x1, x2
beta_y <- normal(0, 1, dim = 3)
sigma_y <- normal(0, 1, truncation = c(0, Inf))

# y depends on x1 and x2, plus some noise
X_y <- cbind(intercept, x1, x2)
mu <- X_y %*% beta_y 
distribution(y) <- normal(mu, sigma_y)
```

**Comment by Maiae** [comment]
Thanks for that. It makes sense. The linear algebra code is much more elegant.
Though, I am having issues when trying to define the model in the second case:

``` r
m <- model(intercept, beta_x1, sigma_x1, beta_y, sigma_y)
```
This will return:
`Error in x$node : $ operator is invalid for atomic vectors`

I wonder if this has something to do with the same `intercept` object being used in both equations.

One other point, which I don't know if it will make any difference: in my data x1 and x2 are known.

**Comment by goldingn** [comment]
The error occurs there is because `intercept` isn't a greta array, it's just an R vector of 1s, so there's no need to draws samples from it. I was being lazy, if I had defined it as `intercept <- ones(n)`, that wouldn't have errored.

However greta should be able to spot that and give a much nicer error! I'll add an issue for that now.

If x1 were data in the above sample then it would be even easier, just do this:
```r
distribution(x1) <- normal(mu_x1, sigma_x1)
```
Though in that case, there's no shared information between the models for y and for x1. Perhaps in your real example there are parameters that are share by the two equations?

**Comment by goldingn** [comment]
That error is in #133, and is now fixed on my goldingn/greta@dev branch.

**Comment by goldingn** [comment]
I think this is resolved now, but please re-open the issue if not!

**Comment by Maiae** [comment]
> Though in that case, there's no shared information between the models for y and for x1. Perhaps in your real example there are parameters that are share by the two equations?

That is correct, no shared information between models. 
Thanks for your help. I was about to close this issue but you beat me to it.
Great work!
