### ISSUE TITLE
Error when running the examples of the mixture-function

### ISSUE THREAD

**Issue by StephanKambach** [greta-dev/greta#150]
When I run the examples of the mixture-function I get the following error:

weights <- uniform(0, 1, dim = 3)
a <- mixture(normal(-3, 0.5),
                     normal(3, 0.5),
                     normal(0, 3),
                     weights = weights)
m <- model(a)

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: reduce_logsumexp() got an unexpected keyword argument 'keepdims'

**Comment by goldingn** [comment]
Ah, looks like a tensorflow version thing. They changed the API in the latest version.

Could you try installing the latest version of tensorflow (1.5 or 1.6)?

As a fix, I'll make this version of greta depend explicitly on the latest tensorflow, so the user gets an error about the version. 

Thanks!

**Comment by goldingn** [comment]
@StephanKambach did you manage to resolve this error? If so I'll close the issue, but happy to help debug if not.

**Comment by goldingn** [comment]
OK, thanks for letting me know!
