### ISSUE TITLE
Bring pkgdown structure up to date?

### ISSUE THREAD

**Issue by pteetor** [greta-dev/greta#162]
The current contents of the `docs` and `vignettes` directories use the structure of an older version of `pkgdown`, and they use custom code (HTML, CSS, and R). The result is a little, uh, opaque. That makes contributing documentation more difficult.

Would you mind if I bring the documentation structure into line with the latest [stable release](http://pkgdown.r-lib.org/index.html) of `pkgdown`?

I can guarantee this change will have pros and cons.

*Pros* - The documentation will be easier to maintain and easier for contributors. It will still fit cleanly into the GitHub Pages site. It will use a standard version of `pkgdown` with little or no custom code. It will have all the contents of the current structure.

*Cons* - It will look different from the [current documentation pages](https://greta-dev.github.io/greta/index.html). The navigation structure will be similar but different. The current site uses colors quite nicely. I'm not sure I can replicate that.

I would understand if you are reluctant to change the current pages. They show a lot of work.

Let me know your thoughts here. Thanks.

**Comment by goldingn** [comment]
Yes, I'm definitely keen for the website build to be brought up to date, especially now pkgdown is more stable!

I'm planning to move the website code to a separate repo, to reduce hit clutter and so that we can show the docs for the CRAN version which lags behind the GitHub release (possibly with a toggle to show the docs for other versions). See #140 for discussion of that. 

That would also require embedding pkgdown in a bunch of custom code (though a refactor is well needed), and would also require me registering a domain name, among other things (e.g. I'd like to add a discourse-backed forum). I'm also keen to keep the aesthetic similar to how it is now.

There are a lot of moving parts there, some of which I'll have to do. But getting the current set up to work with a contemporary version of pkgdown would be a great first step, and I would very glad of help to do it!

**Comment by pteetor** [comment]
OK, sounds good. I'll begin working within a branch of my fork. I can make it visible to you via GitHub Pages, letting you give periodic feedback, checking that it's working for you.

**Comment by goldingn** [comment]
That would be wonderful, thank you!

**Comment by pteetor** [comment]
Nick: I have a working prototype of the new documentation structure, so this is a good time for you to see what it looks like. Please let me know your feedback. You can see the prototype at

[https://pteetor.github.io/greta/](https://pteetor.github.io/greta/)

Caveats:

- The prototype home page is just a *dummy placeholder*. The existing *greta* home page is beautiful, but there are many details contributing to its appearance. Replicating it will take time.
- The current theme is a placeholder. It's colors are not consistent with your *greta* color scheme. (In fact, they clash.)
- There is a new FAQ section. It is populated with some typical questions but not a single answer.
- Several image links are broken.

**Comment by pteetor** [comment]
(Oops. I accidentally closed this issue. So I reopened it. Gotta pay attention to what I'm clicking on.)

**Comment by goldingn** [comment]
Thanks Paul!

I think the FAQ and news sections are a great idea!

Yeah, the homepage is tricky. Does the new pkgdown let you pass it an html index file?

It would be nice if we could get the grouped function references in there too. Not sure whether pkgdown lets you do that - I thought that was where I got the idea and initial code.

Let me know if you need help unpacking what's going on the the current website build. Most of the styling is in a single css file I think, but some of it is in the html and is probably pretty opaque.

**Comment by pteetor** [comment]
Thanks for the positive feedback.

Yes, *pkgdown* will let you supply an HTML file for home page (index). The challenge is integrating that hand-crafted HTML into the nice structure supplied by *pkgdown* - specifically, the menu along the top and the links along the right-hand side. I hoped to preserve that auto-generated structure, both because it's useful to the reader (of course) and because it will be automatically generated and maintained for you -- one less thing to maintain by hand.

Actually, the functions are grouped; the group labels appear along the right-hand side. The grouping is determined by the `roxygen2` comments; which I see as positive because it's one less thing to be maintained by hand. Also, the appearance is different, but at this point I don't know how to customize it.

**Comment by pteetor** [comment]
Nick: I've made the next round of improvements to the package documentation. You can see them at the [same URL](https://pteetor.github.io/greta/) as before. Let me know if you have any additional comments.

The main changes are

- Real home page, replacing the temporary one built from the README
- Initial work on a real FAQ
- Correct color scheme

There are still rough edges, which I will revisit soon. I need to turn my attention to other matters for a while.

**Comment by goldingn** [comment]
Great, yes please open a PR and I'll try to pick it up in a couple of weeks.

Thanks so much for your time and effort on this!

**Comment by pteetor** [comment]
You're welcome. I am glad to contribute.

Forgot to mention: There is a new `DOCUMENTATION.md` file. It describes how to (re-)generate the documentation, how to add new pages, and so forth.

Finally, after you merge the changes, I'll add my examples to yours -- which is what I wanted to do in the first place!
