### ISSUE TITLE
Error advice about namespace conflict for distribution functions

### ISSUE THREAD

**Issue by dhduncan** [greta-dev/greta#170]
After loading greta, if I return to another modelling environment (say, glm,  glmer, or gam) and call `family = poisson` or `binomial`, thereby accepting the canonical link function, I get a helpful warning (see first example in image). 

There are a few contexts where that error message would be helpful, but instead a user will see the far less instructive error that you see in the second and third examples in the image attached.

![screenshot 2018-05-23 10 26 58](https://user-images.githubusercontent.com/5265962/40397046-dd05ea44-5e73-11e8-83c1-7d0306e538f7.png)

**Comment by thorvall** [comment]
Same problem with standard glm:
glm(1 ~ 1,data = data_Train,family = "binomial",control = glm.control(maxit = 50))
Error in distrib("binomial", size, prob, dim) : 
  argument "size" is missing, with no default

Does anyone know how to circumvent this whitout detatching 'greta'

**Comment by goldingn** [comment]
You can use `family = stats::binomial` instead of `family = binomial` in your call to glm.

Which version of greta did you get this error message with @thorvall? This should be fixed in the current release version (it gives a more informative error at least), but I'd very much like to know if not!

**Comment by thorvall** [comment]
Thanks for your quick reply.
its version 0.2.4. 
Just fetching the newest version fra gretadev. (0.2.5). And here the error message is the same. I'm on a windows platform.

**Comment by goldingn** [comment]
Oops, you are right. It's fixed in the dev branch, but wasn't included in the most recent (GitHub) release. Using `devtools::install_github("greta-dev/greta@dev")`, I get:
```r
library(greta)
glm(1 ~ 1, family = "binomial")
```
> ```
> Error: It looks like you're using greta's binomial function in the family argment of
> another model. Maybe you want to use 'family = stats::binomial' instead?
> ```

**Comment by goldingn** [comment]
I hoping to get a 0.3 release out in the next couple of months, which will include all the features and fixes on the dev branch, so this will be resolved then.
