### ISSUE TITLE
allow vector bounds in uniform distributions

### ISSUE THREAD

**Issue by jdyen** [greta-dev/greta#188]
`uniform(min = a, max = b, dim = dim)` only works if `a` and `b` are scalar values. It might be useful to be able to pass `a` and `b` as vectors. @goldingn suggested a simple fix, using:
`(max_vec - min_vec) * uniform(0, 1, dim = dim_of_vec) + min_vec`

**Comment by goldingn** [comment]
also a dump of my thoughts on how to make this work internally here: https://github.com/greta-dev/greta/pull/186#discussion_r197313103

**Comment by goldingn** [comment]
This is implemented on the dev branch
