### ISSUE TITLE
progress bar displays >100% bad

### ISSUE THREAD

**Issue by jdyen** [greta-dev/greta#189]
I sometimes get values >100% bad on progress bar in the sampling phase. Doesn't seem to occur on warmup. Is the number of numerical rejections passed to the progress bar including rejected samples from the warmup?

Possibly here:
https://github.com/greta-dev/greta/blob/322c69c7e4bf739ac2525d1b08674f64d6a4f893/R/inference_class.R#L269
and here:
https://github.com/greta-dev/greta/blob/322c69c7e4bf739ac2525d1b08674f64d6a4f893/R/inference_class.R#L301

**Comment by jdyen** [comment]
actually probably better to look here:
https://github.com/greta-dev/greta/blob/322c69c7e4bf739ac2525d1b08674f64d6a4f893/R/inference_class.R#L479-L487

**Comment by goldingn** [comment]
This is on the dev branch right?

Yeah, there's a little bug in there that misinterprets the output of the Tf probability samplers. My guess is that the TFP sampler returns the log accept ratios for all the leapfrog integration steps in each HMC step (or something) so the number is massively inflated.

I'm planning a blitz of these dev branch issues on my plane ride this weekend. I'll try to get this sorted then.

**Comment by jdyen** [comment]
yep, dev branch.

**Comment by goldingn** [comment]
The issue was that the number of numerical rejections wasn't being reset after the warmup phase, but was being divided by the number of samples so far in the sampling phase. Fixed in my fork of the dev branch now.
