### ISSUE TITLE
How do I extract posterior samples?

### ISSUE THREAD

**Issue by ignacio82** [greta-dev/greta#199]
This is a very basic question but I cannot find this information in the documentation. How do I extract posterior samples after i run `mcmc` ? For example:

```r
library(MASS)
library(greta)

# Create some fake data
N <- 1000
K <- 20
A <- matrix(runif(K^2)*2-1, ncol=K) 
Sigma <- t(A) %*% A
X <- mvrnorm(n = N, mu = runif(K, -10,10), Sigma = Sigma)
betas <- rnorm(K, mean=0, sd = 1)
y <- rnorm(N, 0, 1) + X %*% betas

# data
design <- as_data(scale(X, scale = FALSE))
y_std <- as_data((y - mean(y))/sd(y))

# variables and priors
alpha_ast = normal(0, 1)
beta_ast = normal(0, 1, dim = ncol(design))
sigma_ast = normal(0, 1, truncation = c(0, Inf))

# operation
mu <- alpha_ast + design %*% beta_ast

# likelihood
distribution(y_std) = normal(mu, sigma_ast)

# defining the model

m <- model(alpha_ast, beta_ast, sigma_ast)

# plotting
plot(m)

# sampling
draws <- mcmc(m, n_samples = 1000)  

```

I would like to extract the posterior samples for `y` and `betas`

**Comment by goldingn** [comment]
`draws` is an `mcmc.list` object from the coda package. greta doesn't do any handling of posteriors, that's left to other packages.

You can load coda and use functions in that package to do things with the samples. Maybe codas's `mcmc.subset()` is what you are after? 
https://rdrr.io/cran/coda/man/mcmc.subset.html
