### ISSUE TITLE
Poisson regression model

### ISSUE THREAD

**Issue by howardnewyork** [greta-dev/greta#202]
In the examples page on the Greta website, the Poisson regression model has

lambda <- log(linear_predictor)

But shouldn't it be:

lambda <- exp(linear_predictor)

**Comment by goldingn** [comment]
Yes it should!

Annoyingly, the website is tied to releases of greta at the moment, and I missed this in the latest release.

There's an open PR (#200) that will fix this for the next release, and an issue (#140) covering the need to split the website out from the package release cycle. Hopefully I'll get to the website issue in the next month or so, and fix this then.

**Comment by goldingn** [comment]
Fixed on the dev branch
