### ISSUE TITLE
How to specify initial_values in mcmc

### ISSUE THREAD

**Issue by gosselinf** [greta-dev/greta#203]
Not sure this is an issue but I would like to know in which format to specify the initial values in mcmc. I have tried several but all failed so far.

Exemple:

ModelInits_greta <- function()
{
  asampled<-(rnorm(1,log(3.4),0.3))
  bsampled<-(runif(1,0.2,0.3))
  csampled<-abs((rnorm(1,10,0.3)))
  dsampled<-(runif(1,-7,-5))
  
  
  list (a = exp(asampled),b = bsampled,c =csampled, d = runif(1), disp=0.01,dispb=0.01,alpha=runif(1), logstdstudies.a=runif(1,-6,-5),power=(exp(rnorm(1,0,0.3))))
}		

m<-greta::model(a,b,c,d,disp, alpha,dispb,power,stdstudies.a,logstdstudies.a)

draws <- greta::mcmc(m, n_samples = 1000,initial_values=unlist(ModelInits_greta()))

Sincerely,

Frédéric Gosselin

**Comment by goldingn** [comment]
Unfortunately this is still an issue in the current version. You need to supply it as a vector on the 'unconstrained scale' of the model. Ie. it's not yet accessible to users. 

It's a bit technically tricky to implement, but will be resolved in the next release (in the next month or two). See #105 for a workaround and some discussion

**Comment by goldingn** [comment]
This is implemented on the dev branch now
