### ISSUE TITLE
Specifying a multinomial distribution

### ISSUE THREAD

**Issue by saptarshiguha** [greta-dev/greta#204]
Hello,
I tried fitting this model to some data, and its my first time fitting hierarchical models. Pardon the ignorance, I have much to learn.

Consider, the following matrix (y)

```
      [,1] [,2] [,3] [,4] [,5] [,6] [,7]
 [1,]   86    5    4    3    6   21    7
 [2,]    0    0    0    0    0    0    0
 [3,]    1    2    0    3    3    2    1
 [4,]    1    2    1    0    0    0    1
 [5,]  400   15    2    8    6   10    4
...
```

the rows correspond to indivnidual users and the columns are observartions in each bucket (1 ... 7). Consider the following model,

alpha ~ Exponential(1)
beta ~ Dirichlet(1)
thetai ~ Dirichlet(alpha*beta)
y'ith row  ~ Multinomial(thetai).

I tried the following greta code (`zg` is the above greta array)

```
alpha  = exponential(1)
beta   = dirichlet(ones(7))
thetai = dirichlet(t(beta*alpha))
distribution(zg)  <- multinomial(7, thetai)
```
and got the following error 

```
Error: prob must be a 2D greta array with one column, but has dimensions 1 x 7
```

How would i go about generating the posterior distribution for `thetai`

**Comment by goldingn** [comment]
Yeah, the interface to multivariate distributions is quite clunky in the current version. It's expected that each row in the zg follows the same multinomial distribution, i.e. having the same number of selections (all  the row sums of `zg` should be the same) and the same parameter vector. The parameter vector also needs to be passed in as a column vector, not a row vector (which is what `thetai` is). `dim` needs to say how many rows there are in the random variable.

So this is the expected usage:
```r
# each observation has 4 selections, distributed among the 3 bins
zg <- matrix(c(2, 2, 0,
               0, 0, 4,
               1, 0, 3,
               1, 1, 2,
               2, 1, 1),
             ncol = 3, byrow = TRUE)
alpha <- exponential(1)
beta <- dirichlet(ones(3))
thetai <- dirichlet(t(beta*alpha))
# give the number of selections (4), transpose the parameter vector, give the number of observations (5)
distribution(zg)  <- multinomial(4, t(thetai), dim = 5)
```

It looks like you want different parameters (number of selections at least) for each row. I.e. there are 132 in the first observation, 0 in the second (you may want to remove that, I don't think it's a valid draw from a multinomial), 12 in the third.

Unlike with univariate distributions, I haven't yet implemented variable parameters for multivariate distributions (see #123) but it will be in the next release. For now, you can just define the distribution for each row separately, though there's a performance penalty to doing this, especially as the number of observations gets large:

```r
zg <- matrix(c(86, 5, 4, 3, 6, 21, 7,
               0, 0, 0, 0, 0, 0, 0,
               1, 2, 0, 3, 3, 2, 1),
             ncol = 7, byrow = TRUE)
alpha <- exponential(1)
beta <- dirichlet(ones(7))
thetai <- dirichlet(t(beta*alpha))
for (i in 1:nrow(zg)) {
  row <- zg[i, , drop = FALSE]
  distribution(row)  <- multinomial(sum(row), t(thetai))
}
```

**Comment by saptarshiguha** [comment]
Thank you for the detailed response. Very informative. Yes, that 0 sum row is 0 because i show the first 7 of 100 columns (the parameter vector is actually length 100).

Would this (variable parameters) be available on the dev branch? I'll try the above method, though my data set is a couple of 100K observations ...

**Comment by goldingn** [comment]
Unfortunately it isn't implemented on the dev branch yet. I have a sprint coming up in a couple of weeks and that's high on the to do list, so I'll post progress on #123 when that's done.

I've not seen that error before. It runs fine for me (using the dev branch and TF 1.9). It could be a tensorflow /greta version mismatch, or possibly you just need to clear and restart your R session. I'd recommend giving the dev version a go in any case!

The best starting point for contributing would be [this doc](https://greta-dev.github.io/greta/technical_details.html), though contributing to greta really requires more knowledge of R6 objects and object-oriented programming than it does knowledge of tensorflow. I'm planning to make a bunch of changes so that contributing new operations and distributions is easier, and provide docs on that specifically, but for now it's easiest to try and copy existing code and ask me questions here!

**Comment by saptarshiguha** [comment]
Thanks much. I'll keep watch. Meanwhile, the traceback is

```
> traceback()
9: stop(condition)
8: resignalCondition(future)
7: value.Future(tmp, ...)
6: value(tmp, ...)
5: values.list(fs)
4: values(fs)
3: future.apply::future_lapply(samplers, do("run_chain"), n_samples = n_samples,
       thin = thin, warmup = warmup, verbose = verbose, pb_update = pb_update,
       sequential = sequential, n_cores = n_cores, float_type = float_type,
       from_scratch = from_scratch)
2: run_samplers(samplers = samplers, n_samples = n_samples, thin = thin,
       warmup = warmup, verbose = verbose, pb_update = pb_update,
       n_cores = n_cores, from_scratch = TRUE)
1: mcmc(m, n_samples = 1000)
```

I am using `tensorflow::tf_version()` of 1.9 and the dev branch of greta. tensorflow was installed via virtualenv (using the `install_tensorflow`  call)

**Comment by goldingn** [comment]
Ah, I think it might be that you have an older version of the progress package. there were some API changes in the last release that I patched in the dev version of greta. `install.packages("progress")` should fix that.

**Comment by saptarshiguha** [comment]
Yes, it worked. Thanks much. I'll keep an eye out for development and the next version.
Closing this.

**Comment by saptarshiguha** [comment]
Commenting here (though closed) because the output confused me. Upon running the above i got this for the summary

```
1. Empirical mean and standard deviation for each variable,
   plus standard error of the mean:

                  Mean SD Naive SE Time-series SE
alpha       28616.2559  0        0              0
beta[1,1]       3.3854  0        0              0
beta[1,2]       9.4111  0        0              0
beta[1,3]       2.6150  0        0              0
beta[1,4]       3.9422  0        0              0
beta[1,5]       0.9850  0        0              0
beta[1,6]      11.3325  0        0              0
beta[1,7]       2.3420  0        0              0
thetai[1,1]     6.7971  0        0              0
thetai[1,2]     1.5459  0        0              0
thetai[1,3]     0.5296  0        0              0
thetai[1,4]     0.9889  0        0              0
thetai[1,5]     0.7331  0        0              0
thetai[1,6]     2.6246  0        0              0
thetai[1,7]     1.0517  0        0              0
```

Shouldn't the multinomial parameter $theta$ be between 0 and 1? Is there something i'm obviously missing? My idea of multinomial is that the likelihood is `C* p1^x1/x1! * p2^x2/x2! ... pn^xn/xn!` where `xi` are the values seen in the i'th row `zg` ? In my model i assume all rows are `ni` draws (i.e. variable number of draws per row) from this multinomial .

Thanks much.

**Comment by saptarshiguha** [comment]
Hmm, i think i better wait for multivariate improvements (for this case)
```
^C
>
> zg <- z
> alpha <- exponential(1)
> beta <- dirichlet(ones(ncol(zg)))
> thetai <- dirichlet(t(beta*alpha))
> system.time({
+     pb <- makePB(nrow(zg))
+     for (i in 1:nrow(zg)) {
+         row <- zg[i, , drop = FALSE]
+         distribution(row)  <- multinomial(sum(row), t(thetai))
+         pb$tick()
+     }
+ })

Processing (:extra) []  50% (33771 / 67591) elapsed: 11h ...
```
It was on course to finish in ~ 180 mins, but seems to have gotten stuck ....

**Comment by saptarshiguha** [comment]
Hmm, i think i better wait for multivariate improvements (for this case)
```
^C
>
> zg <- z
> alpha <- exponential(1)
> beta <- dirichlet(ones(ncol(zg)))
> thetai <- dirichlet(t(beta*alpha))
> system.time({
+     pb <- makePB(nrow(zg))
+     for (i in 1:nrow(zg)) {
+         row <- zg[i, , drop = FALSE]
+         distribution(row)  <- multinomial(sum(row), t(thetai))
+         pb$tick()
+     }
+ })

Processing (:extra) []  50% (33771 / 67591) elapsed: 11h ...
```
It was on course to finish in ~ 180 mins, but seems to have gotten slowed down *dramatically*  ....

**Comment by goldingn** [comment]
This is implemented on the dev branch now
