### ISSUE TITLE
Discovering the Tensorflow structure from a greta model

### ISSUE THREAD

**Issue by saptarshiguha** [greta-dev/greta#205]
Hello,

Is there a way to infer the  tensorflow object graph that that greta model creates? 
(apart from the visual diagram). Does greta produce python code?

Thanks much

**Comment by goldingn** [comment]
It doesn't produce python code, but internally it does define r-tensorflow code and objects in an environment, hidden in the model. E.g. if you create a simple model:
```r
library(greta)
a <- normal(0, 1)
b <- a ^ 2
m <- model(b)
```
You can see the tensorflow objects (mostly tensors) in the environment with:
```r
ls(m$dag$tf_environment)
```
>```
> [1] "config"                  "data_1"                  "data_2"                  "data_3"                 
> [5] "distribution_1"          "free_state"              "gradients"               "gradients_adj"          
> [9] "joint_density"           "joint_density_adj"       "n_cores"                 "operation_1"            
> [13] "sess"                    "variable_1"              "variable_1_adj"          "variable_1_free"        
> [17] "variable_1_gradient"     "variable_1_gradient_adj"
> ```
The tensors that make up the graph are named `data_n`, `variable_n`, or `operation_n`. the other objects are used to define the model density, it's gradient or to evaluate things and set up the samplers. Or you can get the tensorflow graph with:
```r
m$dag$tf_graph
```
There are tensorflow methods to manipulate the model, so you could dig around in there. This is well outside the scope of the greta API though, so there's no intention to provide functionality for users to dig around at that level.
