### ISSUE TITLE
plot of computational graph using R's graphic environment

### ISSUE THREAD

**Issue by fkgruber** [greta-dev/greta#206]
Hi
Is there a way to plot the computational graph directly in R (not html) so that we an use png() or pdf() functions to capture the plot?

I use orgmode for my R programming and wanted to get an image into my org file. I imagine the same problem appears when using R markdown.

thanks
Fred

**Comment by goldingn** [comment]
Unfortunately it's not easy - the greta graph is completely integrated with the DiagrammeR package, so html only. There is a [DiagrammeRsvg package](https://github.com/rich-iannone/DiagrammeRsvg) that can be used to capture the html as an image file. It depends on installing some external packages though, so I'm not keen to have it as a dependency (or even a partial dependency, like DiagrammeR). I use it to build the vignettes though, so you can follow that as an example:
https://github.com/greta-dev/greta/blob/master/vignettes/get_started.Rmd
This line grabs the DiagrammeR graph object that's secretly returned by `plot.greta_model()` and creates a png of it
```r
gr <- plot(m)
fname <- "figures/full_graph.png"
DiagrammeR::export_graph(gr,
                         file_name = fname,
                         file_type = 'png',
                         width = 958 * 2,
                         height = 450 * 2)
```

**Comment by goldingn** [comment]
(accidental closure, feel free to close if you're satisfied with the answer!)
