### ISSUE TITLE
optimise slow DAG definition

### ISSUE THREAD

**Issue by goldingn** [greta-dev/greta#211]
Defining a greta model can get really slow for complex (lots of separate operations) models, e.g. those that require a for loop on the R side. That's probably due to the DAG-traversing, recursive R6-iness of the code in the DAG class. It would be worthwhile profiling that code, and possibly finding a DAG-traversal algorithm with better performance.

**Comment by dirmeier** [comment]
Hey Nick, most of the work seems to be going into `tf$gradients` when I benchmark with `profvis(model(parameters))` (~60% if the total time). Any idea how this can be sped up?

**Comment by goldingn** [comment]
Yeah, that's dominant opertion in `model()` for small models (relatively few operations/greta array creations). Probably the only way to speed that up, in general, is to write the model in a more efficient way (use vectorisation/matrix algebra instead of iteration etc.)

I'm more concerned about the performance hit in building the dag object, before even defining the tensorflow model and gradients. E.g. when there's a for loop that scales exponentially with the number of iterations. See e.g. #112, and here for a MRE:

```r
recursive_model <- function (n) {
  a <- normal(0, 1)
  x <- as_data(1)
  for (i in seq_len(n))
    a <- a * x
  model(a)
}

library(greta)

m <- recursive_model(5)
plot(m)
```
<img width="1004" alt="screen shot 2018-08-19 at 11 36 08 am" src="https://user-images.githubusercontent.com/4450731/44304612-1b225900-a3a4-11e8-9a78-fb983e11a499.png">

```r
time_model <- function (n) system.time(recursive_model(n))
n_seq <- seq(1, 51, by = 5)
times <- sapply(n_seq, time_model)
plot(times[1, ], type = "l", lwd = 2)
```
<img width="703" alt="screen shot 2018-08-19 at 11 40 54 am" src="https://user-images.githubusercontent.com/4450731/44304626-c03d3180-a3a4-11e8-8789-8e9eaf59be99.png">

The time taken is exponential in the number of iterations of the for-loop, which isn't good. Let's profile this:

```r
library(profvis)
profvis(recursive_model(20))
```

<img width="577" alt="screen shot 2018-08-19 at 11 45 09 am" src="https://user-images.githubusercontent.com/4450731/44304655-acde9600-a3a5-11e8-969f-49ccabb92bca.png">

`dag$subgraph_membership()` is dominant, and running with different `n`, this is what scales so badly. `dag$subgraph_membership()` is a recursive function, called in `model()` [here](https://github.com/greta-dev/greta/blob/dev/R/greta_model_class.R#L114-L154) to find out whether the dag is in fact composed of separate, unconnected dags.

I'm not sure how critical that check is, it might be possible to find another way this so that the check could be skipped altogether, which would solve this problem.

Another option is to try and find a more efficient way of determining subgraph membership. `dag$subgraph_membership()` recursively calls `node$register_family()`, which is where the time is spent:

<img width="768" alt="screen shot 2018-08-19 at 11 46 52 am" src="https://user-images.githubusercontent.com/4450731/44304692-69d0f280-a3a6-11e8-829e-54a0e96cb3b1.png">

So it's possible this whole structure could be sped up. I'll have to think on this a bit!

**Comment by goldingn** [comment]
This was a useful exercise - I thought it would likely be the nodes defining their tensor counterparts (done in `dag$define_tf()`) that would be slow, so it's good that it's something much less intrinsic to the package!

**Comment by dirmeier** [comment]
Ok, I think I got it. Correct me where I am wrong: the check is needed, cause the model might consist of multiple dags, i.e. sth like:

```
coef1 <- normal(0, 1)
distribution(Sepal.Length) <- normal(coef1, 1)

coe2f <- normal(0, 1)
distribution(Sepal.Width) <- normal(coef2, 1)

model(coef1, coef2)
```

Then for each dag, you need to check if there is a distribution and variable node and a valid target?

**Comment by goldingn** [comment]
Though it looks like the function I wrote to build the adjacency matrix between nodes (dag$adjacency_matrix) is muuuuch quicker. So a quick solution would be to build that once (and store the result) and just extract the subgraph membership from that!

```r
timings <- function (n) {
  m <- recursive_model(n)
  t1 <- system.time(m$dag$subgraph_membership())[3]
  t2 <- system.time(m$dag$adjacency_matrix())[3]
  c(t1, t2)
}
times <- sapply(n_seq, timings)
dim(times)
plot(times[1, ] ~ n_seq, type = "l", lwd = 2)
lines(times[2, ] ~ n_seq, lwd = 2, lty = 2)
```
<img width="624" alt="screen shot 2018-08-22 at 8 41 19 pm" src="https://user-images.githubusercontent.com/4450731/44459111-ba1cae80-a64b-11e8-9e8e-4c97a48f4641.png">

**Comment by goldingn** [comment]
(I assume that finding the subgraphs from an adjacency matrix is a solved problem, and quick to compute. Though it's too late in the day here for me to think about it now)

**Comment by dirmeier** [comment]
> So a quick solution would be to build that once (and store the result) and just extract the subgraph membership from that!

Yeah, exactly. Wouldn't it suffice to, while constructing the initial dag, just store the indices of the subgraph to which a node belongs and at the same time save if the nodes are valid? 

Because, creating a new object from every node seems like a huge overhead
```
 sub_dags <- lapply(self$node_list,
                         function (x) dag_class$new(list(as.greta_array(x))))
```

considering only the memberships are needed?

**Comment by goldingn** [comment]
Yup, definitely a huge overhead!

`dag$build_dag()` doesn't only traverses the tree of connected nodes, to compile a list of those which are connected. The subgraph to which the nodes belong won't obvious in that function, since each node knows only about its parents and children. So we need to first build up the adjacency matrix, and then perform a clustering analysis on it to find nodes that are connected to one another.

I found an efficient algorithm for doing that, and implemented it on the dev branch now: https://github.com/greta-dev/greta/commit/6cf6b898c5a83b42c324aa563c709902776f56d4

It now takes less than a second to define even a large and complex model, and `dag$subgraph_membership()` doesn't even register on the profiler:

```r
profvis(m <- recursive_model(20))
```
<img width="656" alt="screen shot 2018-08-23 at 1 32 55 pm" src="https://user-images.githubusercontent.com/4450731/44503315-082bc380-a6d9-11e8-91f7-3878e5816798.png">

So I'm considering this fixed on the dev branch
