### ISSUE TITLE
Plotting in different colors

### ISSUE THREAD

**Issue by dirmeier** [greta-dev/greta#219]
Hello Nick,

would it be possible to support plotting models in different colors? For presentations or so, I think it is sometimes nice to show the model, but then people might want to stick to their usual colorscheme.

Best,
Simon

**Comment by goldingn** [comment]
You mean in `plot.greta_model`? Definitely!

Should be fairly straightforward, just needs an argument [here](https://github.com/greta-dev/greta/blob/dev/R/greta_model_class.R#L213) for passing a set of colours.

I won't have time to do that any time soon, but would love a PR implementing that!

**Comment by dirmeier** [comment]
I have sth set up already. I'll setup a PR then.

**Comment by goldingn** [comment]
This is now on the dev branch
