### ISSUE TITLE
Kronecker product not working for greta-dev

### ISSUE THREAD

**Issue by urchgene** [greta-dev/greta#221]
Hi,

The kronecker product of two tensors (ie matrices converted by as_data()) is not working.

See below:

Attaching package: ‘greta’

The following objects are masked from ‘package:stats’:

    binomial, poisson

The following objects are masked from ‘package:base’:

    %*%, backsolve, beta, colMeans, colSums, diag, eigen, forwardsolve,
    gamma, rowMeans, rowSums, sweep, tapply

Error in outer(X, Y, FUN, ...) : 
  long vectors not supported yet: array.c:1271
Calls: %*% -> inherits -> kronecker -> .kronecker -> outer
Execution halted

tensorflow-1.10.1 tensorflow-probability-0.3.0 and greta-dev is currently installed.

Thanks.

Uche Godfrey Okeke.

**Comment by goldingn** [comment]
Hi Uche, it works for me when I do something like this:

```r
library(greta)
x <- ones(3, 10)
y <- ones(10, 2)
z <- kronecker(x, y)
```

Could you please post some simple code that shows what isn't working on your machine?

**Comment by urchgene** [comment]
Hi Nick,

Thank you for your prompt reply. The simple example worked which means the problem from mine may be different. Thanks again. I wil try to figure it out.

> library(greta)

Attaching package: ‘greta’

The following objects are masked from ‘package:stats’:

    binomial, poisson

The following objects are masked from ‘package:base’:

    %*%, backsolve, beta, colMeans, colSums, diag, eigen, forwardsolve,
    gamma, rowMeans, rowSums, sweep, tapply

> x <- ones(3, 10)
> y <- ones(10, 2)
> z <- kronecker(x, y)
> 

Uche.

**Comment by urchgene** [comment]
Hi Nick,

I will like to give a feedback on the kronecker error I reported previously.

I found that when i source the script with the model code, kronecker runs very fine. However when I run the code as non-interactive or using Rscript cmd... it fails giving the error : 

Error in outer(X, Y, FUN, ...) :
long vectors not supported yet: array.c:1271
Calls: %*% -> inherits -> kronecker -> .kronecker -> outer
Execution halted

Secondly, I have a question which I do not know anywhere else to ask.
How do i reshape a greta array? 
Thank you.

Uche.

**Comment by goldingn** [comment]
The code above works fine for me when called using RScript, so I don't think that's the issue.

My best guess is that your script loads a package that redefines the kronecker function provided in base R. I think the spam package does that - did you load spam in that script?
If so, you can be explicit that you want to use the base R version (which works for greta arrays) by doing: `base::kronecker()`

**Comment by goldingn** [comment]
One way to reshape a greta array, like with an R array, is to set assign its dimensions like this:
```r
x <- ones(3, 10)
dim(x) <- c(6, 5)
dim(x)
```
> ```
> [1] 6 5
> ```

I'd be interested to know how you would expect to be able to reshape a greta array though. How would you normally reshape an R array?

I may be able to extend greta to enable other commons ways of reshaping (see e.g. #99, which is planned)

**Comment by urchgene** [comment]
Hi Nick,

Thanks so much for your prompt replies!!!

The issue with kronecker may be from loading multiple packages that may overwrite the base. I will check that.

For reshaping an array, the easiest is to define a new array and dump the previous in the dimension you want to. I usually do the following:

x <- matrix(rnorm(10), ncol=1)
y <- matrix(x[,1], ncol=2, nrow=5)

The y matrix relies on the fact that R reads into the matrix by coumn. I can be explicit and specify by row as y <- matrix(x, ncol=2, nrow=5, byrow=TRUE) for pairs.

So it is just to explicitly redefine a new object and read old into it.

**Comment by urchgene** [comment]
Hi Nick,

Kronecker problems persist in a script.

Error in outer(X, Y, FUN, ...) : 
  long vectors not supported yet: array.c:1271
Calls: <Anonymous> -> .kronecker -> outer
Execution halted

code snippet:

### Hierachical Likelihood

# Build XB + u

m = base::kronecker(A, Gcov)
a = m  %*% a_tilde
dim(a) <- c(N,K)

Something is wrong!

**Comment by urchgene** [comment]
Just for records and those who might encounter same issues with kronecker for greta...

Using Rscript cmd, the problem persists but using R CMD BATCH the script runs just fine.

No idea what the issue is.

Thanks again Nick!!!

**Comment by goldingn** [comment]
Sounds like this is cleared up. Glad I could help!
