### ISSUE TITLE
should multinomial distributions always have >1 dimension?

### ISSUE THREAD

**Issue by jdyen** [greta-dev/greta#223]
This check:
https://github.com/greta-dev/greta/blob/db8d2302ab2660db31145a3cd584cfbdf8b429ff/R/utils.R#L464-L469

means that calls to `multinomial(size = scalar, prob = vector)` error because they have `dim = 1`. Is this correct? If so, am I missing an obvious alternative?

**Comment by goldingn** [comment]
The interface to multivariate distributions has changed so that each row is a single realisation. If you have a observation form a multinomial distribution, it needs to be a row vector (can't be a column vector). Similarly, the parameters need to be oriented the same way.

So you could do a multinomial with a single realisation like this:
```r
true_p <- runif(k)
true_p <- true_p / sum(true_p)
multinomial(n, t(true_p))
```

**Comment by goldingn** [comment]
I just realised the details section of the probability docs is out of date. The error message could be more helpful here too. I'll leave this issue open until I can make this a bit clearer in the docs and error messages.

**Comment by jdyen** [comment]
Thanks Nick.

**Comment by goldingn** [comment]
I just fixed the documentation on the dev branch. Now this errors with:
```r
multivariate_normal(rep(0, 3), diag(3))
```
> ```
> Error: the dimension of this distribution must be at least 2 but was 1
> 
> multivariate distributions treat each *row* as a separate realisation - perhaps you need to transpose something? 
> ```

**Comment by goldingn** [comment]
and the docs read:

>For multivariate distributions (`multivariate_normal()`, `multinomial()`, `categorical()`, `dirichlet()`, and `dirichlet_multinomial()`) each row of the output and parameters corresponds to an independent realisation. If a single realisation or parameter value is specified, it must therefore be a row vector (see example). `n_realisations` gives the number of rows/realisations, and `dimension` gives the dimension of the distribution. Ie. a bivariate normal distribution would be produced with `multivariate_normal(..., dimension = 2)`. The dimension can usually be detected from the parameters.

**Comment by goldingn** [comment]
with examples:
```r
# a multivariate normal variable, with correlation between two elements
# note that the parameter must be a row vector
Sig <- diag(4)
Sig[3, 4] <- Sig[4, 3] <- 0.6
theta <- multivariate_normal(t(rep(mu, 4)), Sig)

# 10 independent replicates of that
theta <- multivariate_normal(t(rep(mu, 4)), Sig, n_realisations = 10)

# 10 multivariate normal replicates, each with a different mean vector,
# but the same covariance matrix
means <- matrix(rnorm(40), 10, 4)
theta <- multivariate_normal(means, Sig, n_realisations = 10)
dim(theta)
```
