### ISSUE TITLE
Can GPU-supported TF really accelerate mcmc() ?

### ISSUE THREAD

**Issue by yangchino1** [greta-dev/greta#225]
Hi,
I'm new to greta. I've tested some examples from the greta documentation and of my own using TF 1.10.1 with and without the GPU support, respectively. It seems that the mcmc() takes almost exactly the same time in both situations. However, when running the deep learning example [mnist_cnn](https://github.com/rstudio/keras/blob/master/vignettes/examples/mnist_cnn.R), the GPU acceleration is significant: it takes 9s and 42s for each epoch, respectively, showing that the GPU works. I just wonder if the GPU support can really help accelerate mcmc() automatically, or something I'm not aware of has to be set up?

**Comment by goldingn** [comment]
Another thing to check is the model you are fitting with greta. If it's small, or doesn't do much linear algebra, the GPU is unlikely to be used much. Could you share the code and data?

The mnist_cnn example will be doing a bunch of matrix multiplies, with one dimension of the matrix being about 100,000 (batch_size * img_size ^ 2), so pleanty of linear algebra for the GPU to get its teeth into.

**Comment by yangchino1** [comment]
Here is the code I'm using for testing. This is an example of parameter estimation for the GEV distribution using the so-called "zeros trick", i.e., using the Poisson distribution to achieve the same loglikelihood as of the GEV distribution. It can help implement the GEV distribution in the case of lacking an available PDF.
`library(greta)`
`x <- as_data(c(79.660, 86.810, 59.960, 93.430, 83.740, 70.350, 36.270, 53.800, 68.090, 69.850, 33.470, 52.090, 40.000, 65.490, 28.020, 58.140, 45.740, 38.470, 140.400, 76.680, 90.660, 77.090, 39.110, 107.100, 66.820, 41.270, 78.320, 48.350, 58.550, 56.310, 96.700, 78.520, 71.560, 57.770, 48.250, 99.850, 51.310, 90.960, 65.350, 58.460, 115.500, 43.420, 82.760, 36.480, 95.790, 104.400, 49.710, 63.310, 119.000, 37.950))`
`z <- zeros(50)`
`mu = uniform(0,200)`
`sigma = uniform(1,50)`
`eta = uniform(-1,1)`
`constraint <- 1+eta*(x-mu)/sigma`
`lambda <- (constraint>0)*(log(sigma)+(1+1/eta)*log(abs(constraint))+abs(constraint)^(-1/eta))+(-constraint>0)*100000`
`distribution(z) = poisson(lambda)`
`m <- model(mu,sigma,eta)`
`draws <- mcmc(m,n_samples=10000)`
Compared with the 0.2.5 version I previously used, the dev version shows great improvement in speed especially when running on CPUs. The GPU run took about 3 times longer than the CPU run. This example is probably not suitable for the benchmark use. Hope in the future we can see more guidance to model optimization for greta.

**Comment by goldingn** [comment]
Ah yes, that's not something that would benefit from being run on a GPU.

Yes, there are definitely lots of aspects of modelling to consider with Bayes, HMC and GPUs in general, and greta in particular. Hopefully the planned discussion forum and website documentation will help with those.

**Comment by goldingn** [comment]
@martiningram just ran a big spatial model with MCMC on a GPU, so can confirm the current dev branch is engaging the GPU. I'll close this now, and hopefully we can get some benchmark models and CPU/GPU timings up before too long.
