### ISSUE TITLE
calculate issue

### ISSUE THREAD

**Issue by fernandoramacciotti** [greta-dev/greta#232]
I tried to use the calculate function, but it is not being loaded uppon package request. I tried both in my local machine as well as in Kaggle's kernels, but it didn't work.

It only worked on my local machine with the dev version - is it a bug?

**Comment by goldingn** [comment]
Can you please provide more details about the systems it is/isn't working on, and how you installed greta on those systems?

The most likely reason you don't see the calculate function is that you installed a version of the package that doesn't have it, e.g. the version on CRAN.

**Comment by njtierney** [comment]
Hi there! :wave:

There is a new approach in {greta} to installation, it involves some interactive prompts that arise when you install greta, which help setup a python environment with a specific version of python and other python packages. It should help make everything more reproducible and easier to implement. Are you able to give this a try?

# Install current master branch of greta

```r
# install.packages("remotes")
remotes::install_github("greta-dev/greta")
```

# Restart R

# Load greta with `library(greta)`
```r
library(greta)
```

![image](https://user-images.githubusercontent.com/6488485/124245393-8af44e80-db52-11eb-9083-ecba1390a1fb.png)

# Create a greta model

This will initialise python and trigger internal checks that make sure packages are installed. Something like this code is short and sweet and should trigger this.

```r
model(normal(0,1))
```

![image](https://user-images.githubusercontent.com/6488485/124245709-d27ada80-db52-11eb-902f-b5e7f0c94bd9.png)


Then this:

![image](https://user-images.githubusercontent.com/6488485/124245737-d870bb80-db52-11eb-945c-e7b013656c1e.png)

Follow these instructions:

# Install greta dependencies

```r
install_greta_deps()
```

![image](https://user-images.githubusercontent.com/6488485/124245836-f4745d00-db52-11eb-864c-bf63bfdb14cc.png)

![image](https://user-images.githubusercontent.com/6488485/124245963-11a92b80-db53-11eb-9a56-c1ed87ba296a.png)

![image](https://user-images.githubusercontent.com/6488485/124246257-57fe8a80-db53-11eb-92d2-e132ee108bc1.png)

# Restart R + run `library(greta)`

```r
library(greta)
```

# Create a greta model

```r
model(normal(0,1))
```

![image](https://user-images.githubusercontent.com/6488485/124246524-94ca8180-db53-11eb-9c0b-58bc7a234480.png)

![image](https://user-images.githubusercontent.com/6488485/124246541-998f3580-db53-11eb-8324-0b887ee4d124.png)


Let us know if this works! 😄
