### ISSUE TITLE
kronecker with data

### ISSUE THREAD

**Issue by goldingn** [greta-dev/greta#237]
when kronecker is used with one greta array and one R array, the greta array is coerced into an R array and a garbage result is returned. Need to register S4 methods that coerce R arrays to greta arrays then use the greta array, greta array method

**Comment by Voltemand** [comment]
Hi Nick, 

I've been working on a pull request for this issue but I'm not quite sure how to write tests for it in the testing framework you have developed.

Particularly, I am not sure how to pass both an R array and a greta one to the kronecker method through `check_op`. 

It would, of course, be possible to write some custom test code but I'd much prefer to add tests in the style the rest of the tests are written in!

Any thoughts would very much appreciated.

**Comment by goldingn** [comment]
Yup, it looks like that doesn't fit into the `check_op()` template. The best thing would be to write custom code, using some of the functions that `check_op()` calls, like how eigen in tested (test_functions.R, around line 365)

**Comment by goldingn** [comment]
Thanks!
