### ISSUE TITLE
Plots not displaying on website

### ISSUE THREAD

**Issue by jeffreypullin** [greta-dev/greta#243]
The plots in the analysis section of the website are not displaying properly on Google Chrome.

They instead show: 

![screen shot 2018-11-02 at 4 13 43 pm](https://user-images.githubusercontent.com/34267114/47895120-af3b9100-deba-11e8-83e7-8e0f785b4988.png)

I am using this: 69.0.3497.100 (Official Build) (64-bit) version of Google Chrome. 

I have also checked the page with Safari and see the same issue.

**Comment by goldingn** [comment]
Thanks for letting me know!
I think there's something weird about how netlify is hosting the website, and with relative paths. I'll get in there and have a look this weekend.

**Comment by Voltemand** [comment]
#258

**Comment by Voltemand** [comment]
#258
