### ISSUE TITLE
README.md out of date

### ISSUE THREAD

**Issue by Voltemand** [greta-dev/greta#245]
Some parts of the README.md file displayed on GitHub are out of date. In particular the version number is incorrect and most of the links lead nowhere instead of to the new website.  

I notice that the .README.Rmd file is much more up to date but the .md file it produces isn't displayed on GitHub.

**Comment by Voltemand** [comment]
This is addressed in my current pull request (though I do appreciate it is very low priority) @goldingn

**Comment by goldingn** [comment]
That's really helpful, thanks. Sorry for taking so long to merge it!
