### ISSUE TITLE
Install issue - possibly registry issue?

### ISSUE THREAD

**Issue by lenthomas** [greta-dev/greta#253]
Hi Nick,

I'm trying to install greta, but am stumbling at the tensorflow installation stage.  
`install_tensorflow(method = "conda")`
seems to work no problem, but then
`reticulate::conda_install("r-tensorflow", "tensorflow-probability", pip = TRUE)`
gives the error
`"Did not find VS in registry or in VS140COMNTOOLS env var - exiting"`
Error: Error 1 occurred installing packages into conda environment r-tensorflow

Any thoughts?  Didn't see a similar issue already (open or closed) - apologies if I missed it.

Full session below.

> library(greta)

greta requires TensorFlow (>=1.10.0) and Tensorflow Probability (>=0.3.0), but TensorFlow Probability isn't installed. Use:

    install_tensorflow(method = "conda")
    reticulate::conda_install("r-tensorflow", "tensorflow-probability", pip = TRUE)

to install the latest version.

Attaching package: ‘greta’

The following objects are masked from ‘package:stats’:

    binomial, cov2cor, poisson

The following objects are masked from ‘package:base’:

    %*%, apply, backsolve, beta, chol2inv, colMeans, colSums, diag, eigen,
    forwardsolve, gamma, identity, rowMeans, rowSums, sweep, tapply

> install_tensorflow(method = "conda")

Remove all packages in environment C:\Users\len\AppData\Local\conda\conda\envs\r-tensorflow:

## Package Plan ##

  environment location: C:\Users\len\AppData\Local\conda\conda\envs\r-tensorflow

The following packages will be REMOVED:

    absl-py:              0.6.1-py36_1000          conda-forge
    asn1crypto:           0.24.0-py36_1003         conda-forge
    astor:                0.7.1-py_0               conda-forge
    blas:                 1.0-mkl                             
    ca-certificates:      2018.10.15-ha4d7672_0    conda-forge
    certifi:              2018.10.15-py36_1000     conda-forge
    cffi:                 1.11.5-py36hfa6e2cd_1001 conda-forge
    chardet:              3.0.4-py36_1003          conda-forge
    cryptography:         2.3.1-py36h74b6da3_0     conda-forge
    cryptography-vectors: 2.3.1-py36_1000          conda-forge
    freetype:             2.9.1-he8b6a0d_1004      conda-forge
    gast:                 0.2.0-py_0               conda-forge
    grpcio:               1.14.1-py36he089993_0    conda-forge
    h5py:                 2.8.0-py36h54c06b0_1003  conda-forge
    hdf5:                 1.10.2-vc14_0            conda-forge [vc14]
    icc_rt:               2017.0.4-h97af966_0                 
    idna:                 2.7-py36_1002            conda-forge
    intel-openmp:         2019.1-144                          
    jpeg:                 9c-hfa6e2cd_1001         conda-forge
    keras:                2.2.4-py36_0             conda-forge
    keras-applications:   1.0.4-py_1               conda-forge
    keras-preprocessing:  1.0.2-py_1               conda-forge
    libgpuarray:          0.7.6-vc14_0             conda-forge [vc14]
    libpng:               1.6.34-vc14_0            conda-forge [vc14]
    libprotobuf:          3.6.1-h1a1b453_1000      conda-forge
    libtiff:              4.0.9-vc14_0             conda-forge [vc14]
    mako:                 1.0.7-py_1               conda-forge
    markdown:             2.6.11-py_0              conda-forge
    markupsafe:           1.1.0-py36hfa6e2cd_1000  conda-forge
    mkl:                  2018.0.3-1                          
    mkl_fft:              1.0.6-py36_0             conda-forge
    mkl_random:           1.0.2-py36_0             conda-forge
    numpy:                1.15.4-py36ha559c80_0               
    numpy-base:           1.15.4-py36h8128ebf_0               
    olefile:              0.46-py_0                conda-forge
    openssl:              1.0.2o-vc14_0            conda-forge [vc14]
    pillow:               5.3.0-py36h9a613e6_1000  conda-forge
    pip:                  18.1-py36_0                         
    protobuf:             3.6.1-py36he025d50_1001  conda-forge
    pycparser:            2.19-py_0                conda-forge
    pygpu:                0.7.6-py36h452e1ab_1000  conda-forge
    pyopenssl:            18.0.0-py36_1000         conda-forge
    pyreadline:           2.1-py36_1000            conda-forge
    pysocks:              1.6.8-py36_1002          conda-forge
    python:               3.6.6-he025d50_0         conda-forge
    pyyaml:               3.13-py36hfa6e2cd_1001   conda-forge
    requests:             2.20.1-py36_1000         conda-forge
    scipy:                1.1.0-py36h4f6bf74_1                
    setuptools:           40.6.2-py36_0                       
    six:                  1.11.0-py36_1001         conda-forge
    tensorboard:          1.10.0-py36_0            conda-forge
    tensorflow:           1.10.0-py36_0            conda-forge
    tensorflow-hub:       0.1.1-py_0               conda-forge
    termcolor:            1.1.0-py_2               conda-forge
    theano:               1.0.3-py36h6538335_1001  conda-forge
    tk:                   8.6.8-vc14_0             conda-forge [vc14]
    urllib3:              1.23-py36_1001           conda-forge
    vc:                   14-0                     conda-forge
    vs2015_runtime:       14.15.26706-h3a45250_0              
    vs2015_win-64:        14.0.25123-h17c34da_3    conda-forge
    werkzeug:             0.14.1-py_0              conda-forge
    wheel:                0.32.3-py36_0                       
    win_inet_pton:        1.0.1-py36_1002          conda-forge
    wincertstore:         0.2-py36h7fe50ca_0                  
    yaml:                 0.1.7-vc14_0             conda-forge [vc14]
    zlib:                 1.2.11-vc14_0            conda-forge [vc14]

Creating r-tensorflow conda environment for TensorFlow installation...
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\len\AppData\Local\conda\conda\envs\r-tensorflow

  added / updated specs: 
    - python=3.6

The following NEW packages will be INSTALLED:

    certifi:        2018.10.15-py36_0     
    pip:            18.1-py36_0           
    python:         3.6.7-h33f27b4_1      
    setuptools:     40.6.2-py36_0         
    vc:             14.1-h0510ff6_4       
    vs2015_runtime: 14.15.26706-h3a45250_0
    wheel:          0.32.3-py36_0         
    wincertstore:   0.2-py36h7fe50ca_0    

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use:
# > activate r-tensorflow
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\len\AppData\Local\conda\conda\envs\r-tensorflow

  added / updated specs: 
    - h5py
    - keras
    - pillow
    - pyyaml
    - requests
    - scipy
    - tensorflow-hub
    - tensorflow==1.10.0

The following NEW packages will be INSTALLED:

    absl-py:              0.6.1-py36_1000          conda-forge
    asn1crypto:           0.24.0-py36_1003         conda-forge
    astor:                0.7.1-py_0               conda-forge
    blas:                 1.0-mkl                             
    ca-certificates:      2018.10.15-ha4d7672_0    conda-forge
    cffi:                 1.11.5-py36hfa6e2cd_1001 conda-forge
    chardet:              3.0.4-py36_1003          conda-forge
    cryptography:         2.3.1-py36h74b6da3_0     conda-forge
    cryptography-vectors: 2.3.1-py36_1000          conda-forge
    freetype:             2.9.1-he8b6a0d_1004      conda-forge
    gast:                 0.2.0-py_0               conda-forge
    grpcio:               1.14.1-py36he089993_0    conda-forge
    h5py:                 2.8.0-py36h54c06b0_1003  conda-forge
    hdf5:                 1.10.2-vc14_0            conda-forge [vc14]
    icc_rt:               2017.0.4-h97af966_0                 
    idna:                 2.7-py36_1002            conda-forge
    intel-openmp:         2019.1-144                          
    jpeg:                 9c-hfa6e2cd_1001         conda-forge
    keras:                2.2.4-py36_0             conda-forge
    keras-applications:   1.0.4-py_1               conda-forge
    keras-preprocessing:  1.0.2-py_1               conda-forge
    libgpuarray:          0.7.6-vc14_0             conda-forge [vc14]
    libpng:               1.6.34-vc14_0            conda-forge [vc14]
    libprotobuf:          3.6.1-h1a1b453_1000      conda-forge
    libtiff:              4.0.9-vc14_0             conda-forge [vc14]
    mako:                 1.0.7-py_1               conda-forge
    markdown:             2.6.11-py_0              conda-forge
    markupsafe:           1.1.0-py36hfa6e2cd_1000  conda-forge
    mkl:                  2018.0.3-1                          
    mkl_fft:              1.0.6-py36_0             conda-forge
    mkl_random:           1.0.2-py36_0             conda-forge
    numpy:                1.15.4-py36ha559c80_0               
    numpy-base:           1.15.4-py36h8128ebf_0               
    olefile:              0.46-py_0                conda-forge
    openssl:              1.0.2o-vc14_0            conda-forge [vc14]
    pillow:               5.3.0-py36h9a613e6_1000  conda-forge
    protobuf:             3.6.1-py36he025d50_1001  conda-forge
    pycparser:            2.19-py_0                conda-forge
    pygpu:                0.7.6-py36h452e1ab_1000  conda-forge
    pyopenssl:            18.0.0-py36_1000         conda-forge
    pyreadline:           2.1-py36_1000            conda-forge
    pysocks:              1.6.8-py36_1002          conda-forge
    pyyaml:               3.13-py36hfa6e2cd_1001   conda-forge
    requests:             2.20.1-py36_1000         conda-forge
    scipy:                1.1.0-py36h4f6bf74_1                
    six:                  1.11.0-py36_1001         conda-forge
    tensorboard:          1.10.0-py36_0            conda-forge
    tensorflow:           1.10.0-py36_0            conda-forge
    tensorflow-hub:       0.1.1-py_0               conda-forge
    termcolor:            1.1.0-py_2               conda-forge
    theano:               1.0.3-py36h6538335_1001  conda-forge
    tk:                   8.6.8-vc14_0             conda-forge [vc14]
    urllib3:              1.23-py36_1001           conda-forge
    vs2015_win-64:        14.0.25123-h17c34da_3    conda-forge
    werkzeug:             0.14.1-py_0              conda-forge
    win_inet_pton:        1.0.1-py36_1002          conda-forge
    yaml:                 0.1.7-vc14_0             conda-forge [vc14]
    zlib:                 1.2.11-vc14_0            conda-forge [vc14]

The following packages will be UPDATED:

    certifi:              2018.10.15-py36_0                    --> 2018.10.15-py36_1000 conda-forge

The following packages will be DOWNGRADED:

    python:               3.6.7-h33f27b4_1                     --> 3.6.6-he025d50_0     conda-forge
    vc:                   14.1-h0510ff6_4                      --> 14-0                 conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Installation complete.

Restarting R session...

> reticulate::conda_install("r-tensorflow", "tensorflow-probability", pip = TRUE)

C:\Users\len\Documents>python C:\Users\len\AppData\Local\conda\conda\envs\r-tensorflow\etc\keras\load_config.py  1>temp.txt 

C:\Users\len\Documents>set /p KERAS_BACKEND= 0<temp.txt 

C:\Users\len\Documents>del temp.txt 

C:\Users\len\Documents>python -c "import keras"  1>nul 2>&1 

C:\Users\len\Documents>if errorlevel 1 (
ver  1>nul  
 set "KERAS_BACKEND=theano"  
 python -c "import keras"  1>nul 2>&1 
) 

C:\Users\len\Documents>SET DISTUTILS_USE_SDK=1 

C:\Users\len\Documents>SET MSSdk=1 

C:\Users\len\Documents>SET platform= 

C:\Users\len\Documents>IF /I [AMD64] == [amd64] set "platform=true" 

C:\Users\len\Documents>IF /I [] == [amd64] set "platform=true" 

C:\Users\len\Documents>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" ) 

C:\Users\len\Documents>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /v InstallDir') do SET "VSINSTALLDIR=%B" 
ERROR: The system was unable to find the specified registry key or value.

C:\Users\len\Documents>if "" == "" (set "VSINSTALLDIR=" ) 

C:\Users\len\Documents>if "" == "" (
ECHO "Did not find VS in registry or in VS140COMNTOOLS env var - exiting"  
 exit 1 
) 
"Did not find VS in registry or in VS140COMNTOOLS env var - exiting"
Error: Error 1 occurred installing packages into conda environment r-tensorflow

**Comment by lenthomas** [comment]
Should have said: Windows 10; R 2.5.1

**Comment by goldingn** [comment]
Thanks Len, this is a new one for me.

Looks like conda didn't install correctly. Possibly because of some conflict with Visual Studio? 

Windows stuff confuses me, but I've googled around a bit. I'm guessing you have a 64 bit windows install (`sessionInfo()` will tell you), but is it possible you accidentally installed the 32 bit version of conda?

If so, uninstalling conda and reinstalling the 64 bit version should do it.

**Comment by lenthomas** [comment]
Thanks Nick - Yes, it was 64 bit R, and 64 bit Anaconda.  I uninstalled and tried again, but same result.  I may try uninstalling Visual studio tomorrow, so if that does it.

**Comment by goldingn** [comment]
Hmmm, that's annoying.

You could try installing something with conda from either the conda GUI or the commandline, to rule the R component either in or out as the point of failure?

Sorry I can't be more help!

If you want to have a play with greta in the meantime, try going here and signing in with your github account: bit.ly/try_greta
You'll only have 1 cpu and little ram, but it should give you a feel for it!

**Comment by rdinnager** [comment]
Did you ever solve this issue @lenthomas ? I'm getting the same issue after installing the latest greta version.. :( Also using Windows 10.

**Comment by lenthomas** [comment]
Nope, sorry -- ended up writing custom MCMC code with the student who's problem we were working on, as a learning exercise for the student.  Sorry to admit that I never went back to battling the install when the need went away.  I'll likely try again at some point when I get a little time - meantime good luck.  As you can see, Nick was very helpful in making suggestions.

**Comment by rdinnager** [comment]
I finally found a solution to this problem. The error happens when trying to activate the 'r-tensorflow' environment in conda. I found this thread on stackoverflow that seemed to be the same problem: https://stackoverflow.com/questions/53635462/anaconda-prompt-closes-immediately-the-system-was-unable-to-find-the-specified
The recommended solution was to just delete the .bat file that seemed to be causing the problem (vs2015_compiler_vars.bat). I searched for that file, found two copies, and deleted them both for good measure. Once I did this, the error went away. I have no idea what this .bat file is for, or if deleting it will cause other problems down the road, but so far `greta` seems to work fine without it. Hope this helps anyone else getting this issue!

**Comment by Zeroto521** [comment]
I got this problem also, but still not a solution.

## When's happen

Using `conda` to create a new env for tensorflow.

1. Using cmd `conda create -n ml`
1. Using cmd `activate ml`
1. Using cmd `conda install tensorflow`
    > No any problem, and the script can run
1. Using cmd `conda install tensorflow-gpu`
    > It still ok in this shell when trying the script
1. Open another shell, try to cmd `activate ml`, then it happened

## Error info

Some error info as follows

```shell
C:\Users\Zero>activate ml

C:\Users\Zero>python C:\Software\Miniconda3\envs\ml\etc\keras\load_config.py  1>temp.txt

C:\Users\Zero>set /p KERAS_BACKEND= 0<temp.txt

C:\Users\Zero>del temp.txt

C:\Users\Zero>python -c "import keras"  1>nul 2>&1

C:\Users\Zero>if errorlevel 1 (
ver  1>nul
 set "KERAS_BACKEND=theano"
 python -c "import keras"  1>nul 2>&1
)

C:\Users\Zero>SET DISTUTILS_USE_SDK=1

C:\Users\Zero>SET MSSdk=1

C:\Users\Zero>SET platform=

C:\Users\Zero>IF /I [AMD64] == [amd64] set "platform=true"

C:\Users\Zero>IF /I [] == [amd64] set "platform=true"

C:\Users\Zero>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" )

C:\Users\Zero>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /v InstallDir') do SET "VSINSTALLDIR=%B"
错误: 系统找不到指定的注册表项或值。

C:\Users\Zero>if "" == "" (set "VSINSTALLDIR=" )

C:\Users\Zero>if "" == "" (
ECHO "Did not find VS in registry or in VS140COMNTOOLS env var - exiting"
 exit 1
)
"Did not find VS in registry or in VS140COMNTOOLS env var - exiting"
```

**Comment by zhuang-hao-ming** [comment]
@Zeroto521  


I got this problem also. I can not find a solution after searching the entire internet.
Finally i try the method suggested by https://stackoverflow.com/questions/2667069/cannot-find-vcvarsall-bat-when-running-a-python-script.
I add a new env var by 
```
SET VS90COMNTOOLS=%VS100COMNTOOLS%
```
and finally it work.

**Comment by goldingn** [comment]
I'd really appreciate it if anyone could test whether installing the new version of greta (0.3.1) and following the on-screen installation instructions for installing the right tensorflow versions will resolve this issue.

**Comment by yanghc01** [comment]
I met the problem too

**Comment by summerela** [comment]
I'm also having this issue on Windows 10 with Anaconda 64bit.

**Comment by parizad2500** [comment]
I could solve this problem by deleting "etc" folder in the installed directory C:\Users\.conda\envs\tf

(installing keras  in tensorflow environment)
C:\Users\Ali>SET MSSdk=1

C:\Users\Ali>SET platform=

C:\Users\Ali>IF /I [AMD64] == [amd64] set "platform=true"

C:\Users\Ali>IF /I [] == [amd64] set "platform=true"

C:\Users\Ali>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" )

C:\Users\Ali>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /v InstallDir') do SET "VSINSTALLDIR=%B"
ERROR: The system was unable to find the specified registry key or value.

C:\Users\Ali>if "" == "" (set "VSINSTALLDIR=" )

C:\Users\Ali>if "" == "" (
ECHO "WARNING: Did not find VS in registry or in VS140COMNTOOLS env var - your compiler may not work"
 GOTO End
)

**Comment by njtierney** [comment]
Hi there! :wave:

There is a new approach in {greta} to installation, it involves some interactive prompts that arise when you install greta, which help setup a python environment with a specific version of python and other python packages. It should help make everything more reproducible and easier to implement. Are you able to give this a try?

# Install current master branch of greta

```r
# install.packages("remotes")
remotes::install_github("greta-dev/greta")
```

# Restart R

# Load greta with `library(greta)`
```r
library(greta)
```

![image](https://user-images.githubusercontent.com/6488485/124245393-8af44e80-db52-11eb-9083-ecba1390a1fb.png)

# Create a greta model

This will initialise python and trigger internal checks that make sure packages are installed. Something like this code is short and sweet and should trigger this.

```r
model(normal(0,1))
```

![image](https://user-images.githubusercontent.com/6488485/124245709-d27ada80-db52-11eb-902f-b5e7f0c94bd9.png)


Then this:

![image](https://user-images.githubusercontent.com/6488485/124245737-d870bb80-db52-11eb-945c-e7b013656c1e.png)

Follow these instructions:

# Install greta dependencies

```r
install_greta_deps()
```

![image](https://user-images.githubusercontent.com/6488485/124245836-f4745d00-db52-11eb-864c-bf63bfdb14cc.png)

![image](https://user-images.githubusercontent.com/6488485/124245963-11a92b80-db53-11eb-9a56-c1ed87ba296a.png)

![image](https://user-images.githubusercontent.com/6488485/124246257-57fe8a80-db53-11eb-92d2-e132ee108bc1.png)

# Restart R + run `library(greta)`

```r
library(greta)
```

# Create a greta model

```r
model(normal(0,1))
```

![image](https://user-images.githubusercontent.com/6488485/124246524-94ca8180-db53-11eb-9c0b-58bc7a234480.png)

![image](https://user-images.githubusercontent.com/6488485/124246541-998f3580-db53-11eb-8324-0b887ee4d124.png)


Let us know if this works! 😄

**Comment by lenthomas** [comment]
Yeah, baby, groovy.  Worked like a dream.  Only hiccup was that I'm on a new machine that did not have Python on it, so after the first

`model(normal(0,1))`

I got the message

```
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: Y
```

I said `Y` and it went ahead and installed miniconda in my `AppData` directory, which is fine.  I then got, as expected, the message

```
Error: We have detected that you do not have the expected python packages setup. You can set these up using:

	`install_greta_deps()`
```

and everything proceeded as you predicted.  So, up and running now.  I'll go ahead and close this issue.  Thanks for your help @njtierney and, earlier, @goldingn .

**Comment by njtierney** [comment]
Fantastic news!

**Comment by njtierney** [comment]
Awesome!
