### ISSUE TITLE
Broken images in the site's Analyses pages

### ISSUE THREAD

**Issue by DesiQuintans** [greta-dev/greta#258]
Hi, the example analyses pages on the `greta` website have images that are not loading. Are the pointing to non-existent files? <https://greta-stats.org/articles/analyses/election_88.html>

**Comment by Voltemand** [comment]
Hi @DesiQuintans, this issue is has already been raised in #243 where Nick has already responded (something to do with relative paths apparently) so I think we should close this just to avoid duplication.

**Comment by DesiQuintans** [comment]
Ah, pardon me. I did a search for 'images' and 'example' but those words weren't used in the issue so I didn't find it.

**Comment by Voltemand** [comment]
Ah, no worries! Funny that we used different words to describe the same problem.
