### ISSUE TITLE
Incompatible with the latest NumPy v1.16

### ISSUE THREAD

**Issue by yangchino1** [greta-dev/greta#261]
When using `model()` to define a model, I got a series of the following repeated error message:
> C:\PROGRA~1\Python36\lib\site-packages\numpy\lib\type_check.py:546: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead  'a.item() instead', DeprecationWarning, stacklevel=1)

**Comment by Voltemand** [comment]
Hi yangchino, 

greta doesn't contain any of our own python code it only interfaces to python libraries - **tensorflow** and **tensorflow-probability** so hopefully the maintainers of those packages will fix this issue in their next releases. 

Thanks!

**Comment by flyaflya** [comment]
Please see https://forum.greta-stats.org/t/installing-greta-robust-instructions-as-of-march-31-2019/98

I have given some install instructions for greta that can use tensorflow-probability=0.6.0 and then these deprecation warnings go away.

**Comment by goldingn** [comment]
These deprecation messages should have dissapeared in the latest release. Please open a new issue if you see some more (I won't be surprised if you do!)
