### ISSUE TITLE
Printing draws

### ISSUE THREAD

**Issue by jeffreypullin** [greta-dev/greta#262]
One of the nice features of using **rstan** is the informative summary displayed after printing a `stanfit` object which includes mean, sd, quantiles and R-hat statistics for each variable. This allows instant diagnosis of major problems and inspection of key quantities.

Currently in **greta** draws from the `mcmc` function are of type `mcmc.list` which no real print method and only a passable summary method (which does not include R-hat statistics). (I know that the `mcmc.list` object is used for compatibility with other packages.) I think that adding a better 'viewing' methods for this object (particularly a better print method) would streamline the workflow of **greta** and make it more intuitive 

My suggestion would be to either: 
- Define a print method for  `mcmc.list` in **greta**
- Create a new class (possibly `greta_draws` say which would provide such a pretty printing method. 

Let me know if this is something you think **greta** needs - I'd be more than happy to submit a pull request. 

Thanks!

**Comment by goldingn** [comment]
I think we discussed this one in person, but for the record:

Yes, I totally agree!

greta does some weird things to the `mcmc.list` object (adding an attribute that enables `calculate()`), so adding an additional class that extends `mcmc.list` would make sense.

In addition to nice printing and plotting methods, that class could have it's own version of coda functions like `thin()`, which currently won't work properly with `calculate()`

**Comment by Voltemand** [comment]
We did, but thanks for the follow up. We should add this to the TODO list. Speaking of which is there a publicly available priorities/to implement list anywhere? I think that would be a good thing to have so people can see what is being planned and help if they can. 

Regarding a name for the class - I like `greta_draws`.

**Comment by goldingn** [comment]
I'm using issues as a to do list really. Though we should add a milestone (for version 0.4.0) and add the most important issues to that.
