### ISSUE TITLE
32/64 bit compatibility issue ?

### ISSUE THREAD

**Issue by tiboloic** [greta-dev/greta#268]
Hi all,

I just installed greta on my new desktop computer, windows 64bits, R 64-bit.
After installing greta and trying to run the iris example, `mcmc` fails with this error which suggests a 32 bits to  64 bits problem:

`> draws <- mcmc(m, n_samples = 1000)`
`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Tensor conversion requested dtype int64 for Tensor with dtype int32: 'Tensor("Placeholder_14:0", dtype=int32)'`

`Detailed traceback: `
  `File C:\Users\loithi\AppData\Local\CONTIN\ANACON\envs\R-TENS\lib\site-packages\tensorflow_probability\python\mcmc\sample.py, line 216, in sample_chain
    name="num_steps_between_results")`
  `File "C:\Users\loithi\AppData\Local\CONTIN\ANACON\envs\R-TENS\lib\site-packages\tensorflow\python\framework\ops.py", line 1050, in convert_to_tensor
    as_ref=False)`
 ` File "C:\Users\loithi\AppData\Local\CONTIN\ANACON\envs\R-TENS~1\lib\site-packages\tensorflow\python\framework\ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)`
 ` File "C:\Users\loithi\AppData\Local\CONTIN\ANACON\envs\R-TENS\lib\site-packages\tensorflow\python\framework\ops.py", line 983, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))`

Any suggestion ?

**Comment by goldingn** [comment]
Could you please install the latest GitHub version and try again?

```
devtools::install_github("greta-dev/greta")
```

There was a change in Tensorflow Probability that caused this, now fixed on GitHub.

If that doesn't work, please post a reproducible example and I'll see what's up.

**Comment by tiboloic** [comment]
That solved the problem. Thanks Nick, much appreciated

**Comment by fkgruber** [comment]
I'm having the same problem and installing the github version is not solving it
I did:
```
library(reticulate)
reticulate::use_condaenv("tf2")
library(greta)
 int <- normal(0, 10)
 coef <- normal(0, 10)
 sd <- cauchy(0, 3, truncation = c(0, Inf))

 ## linear predictor
 mu <- int + coef * attitude$complaints

 ## observation model
 distribution(attitude$rating) <- normal(mu, sd)
 m = model(mu, sd)
 draws <- mcmc(m, n_samples = 1000, chains = 4)
```

and got:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   RuntimeError: Evaluation error: ValueError: Tensor("mcmc_sample_chain_4/trace_scan/while/Const:0", shape=(3,), dtype=int32) must be from the same graph as Tensor("leapfrog_integrate_one_step/add:0", shape=(None, 3), dtype=float64).
> 
> Detailed traceback: 
>   File "/Users/fred/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 1796, in split
>     value=value, size_splits=size_splits, axis=axis, num_split=num, name=name)
>   File "/Users/fred/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 9145, in split_v
>     num_split=num_split, name=name)
>   File "/Users/fred/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 307, in _apply_op_helper
>     g = ops._get_graph_from_inputs(_Flatten(keywords.values()))
>   File "/Users/fred/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 5883, in _get_graph_from_inpu
> >
