### ISSUE TITLE
Replicate the type of multivariate_Normal in PyMC3

### ISSUE THREAD

**Issue by urchgene** [greta-dev/greta#275]
The multivariate normal in Greta seems different from that in PyMC3. 

In PyMC3, the multivariate normal can take a matrix, use the rows of the matrix as $\mu$ and accept the dimension of the rows for $\Sigma$. This is very important framework cos it makes scalability for mixed models much easier and can be based on conditional means instead of an large error covariance.

Can this be implemented?

Or maybe could you show how to make a custom distribution so I can use the dmvn() function in R's LaplacesDemon to do this. This dmvn is exactly what PYMC3 has.

I have run many tests on Greta and PyMC3 with different results and found this to be the culprit.

Thanks.

Uche.
---

**Comment by urchgene** [comment]
@benmarwick @michaelquinn32 

I tried to do a custom multivariate normal that go row-wise:

I am having problems with the dim variable. Please can you help to show how it works?

```r{library(greta)
library(R6)  ## is a must
library(tensorflow)


#### utility functions 

# tf logdet
tf_logdet <- function(x)
  tf$linalg$logdet(x)

tf_matmul <- function(x, y)
  tf$linalg$matmul(x, y)

tf_inv <- function(x)
  tf$linalg$inv(x)

tf_shape <- function(x)
  tf$shape(x)

tf_rowsums <- greta::tf_rowsums
tf_sum <- greta:::tf_sum


mvn_distribution <- R6Class(
  "multivariate_normal_distribution_matrix_valued",
  inherit = distribution_node,
  public = list(
    initialize = function(mu, Sigma, X, dim) {
      mu <- as.greta_array(mu)
      Sigma <- as.greta_array(Sigma)
      X <- as.greta_array(X)
      dim <- check_dims(Sigma, target_dim = dim)
      super$initialize("multivariate_normal_matrix_valued", dim, discrete = FALSE)
      self$add_parameter(mu, "mu")
      self$add_parameter(Sigma, "Sigma")
      self$add_parameter(X, "X")
    },
    
    tf_distrib = function(parameters, dag) {
      mu <- parameters$mu
      Sigma <- parameters$Sigma
      X <- parameters$X
      log_prob <- function(k) {
      	k = tf_shape(Sigma)
      	Omega = tf_inv(Sigma)
      	ss = X - mu
      	z = tf_rowsums(tf_mul(tf_matmul(ss, Omega), ss))
      	tf_sum(-0.5 * (k * log(2 * pi) + tf_logdet(Sigma)) - (0.5 * z))
      }
      
      list(log_prob = log_prob, cdf = NULL, log_cdf = NULL)
    },
    
    tf_cdf_function = NULL,
    tf_log_cdf_function = NULL
  )
)



mvn <- function(mu, Sigma, X, dim = NULL) {
  distrib("multivariate_normal_matrix_valued",mu, Sigma, X, dim)
}
}

```

Thanks.

**Comment by goldingn** [comment]
Hi Uche,

I don't quite understand what you are after. Do you mean you want it to accept a 2D (n x m) array for mu and a 3D (m x m x n) array for Sigma, so that each row of the resulting 2D (n x m) variables has a different covariance?

Or do you just want a different mu for each row, but the same covariance for all rows? If so, greta can already do this.

It would be really helpful if you could provide a [reprex](https://www.tidyverse.org/help/) of your problem so it's clear what you are trying to do and what's going wrong.

**Comment by urchgene** [comment]
hi @goldingn 

Thanks for your reply.

I mean the second case you mentioned.

Accept a 2D(nxm) mu and a 2D(mxm) covariance matrix while using a different mu as each row.
Please can you show an example of how greta does this already.

Thanks.

**Comment by goldingn** [comment]
There's an example of this in the helpfile for greta's probability distributions, which you can get to with `?multivariate_normal`. It looks something like this:

```r
mu <- matrix(rnorm(40), 10, 4)
Sigma <- diag(4)
Sigma[3, 4] <- Sigma[4, 3] <- 0.6

theta <- multivariate_normal(mu, Sigma, n_realisations = 10)
```

obviously `mu` and `Sigma` could be greta arrays instead of numeric matrices

**Comment by urchgene** [comment]
@goldingn Thanks a lot !! That is exactly what I wanted.

**Comment by goldingn** [comment]
Sounds like this is resolved so I'll close the issue. Feel free to open a new one, or post on [the forum](https://forum.greta-stats.org), if you have more questions.
