### ISSUE TITLE
Log Posterior (LP) as optimization cost function instead of Log Likelihood.

### ISSUE THREAD

**Issue by urchgene** [greta-dev/greta#276]
Hi @goldingn,

Before I start I wanna say thanks again for your prompt reply on issues!!! 

So if using Opt or mcmc, usually the target cost I have seen in most examples is the log-likelihood. Mainly this for example:

distribution(Y) <- multivariate_normal(mu, sigma). This I call LogLik.

However of interest may be a LP as:
LogLik + logprob(prior1) + logprob(prior2) etc. as the cost function.

How can this be done in greta? 

logprob is defined as density(params, prior_sample) and params are same one used to get prior sample.

Thanks.

Uche.

**Comment by goldingn** [comment]
If you create your variables with distributions, like this:
```r
coef <- normal(0, 10, dim = 3)
```
then the distribution defines the prior, and the target density is the posterior (LogLik + logprob(prior) as you have it).

If you create your variables with `variable()` like this:
```r
coef <- variable(dim = 3)
```
then no priors are defined and the target density is the likelihood (just LogLik)*. 

So you just right out your generative model, and greta works out which are the priors (if any) and likelihood, and combines them into the target density.

---

*There's a one caveat to that: you need to think about log jacobian adjustments if your `variable()` uses the `lower` or `upper` arguments. See [here](https://forum.greta-stats.org/t/frequentist-implementation/94/2?u=nick), or the Stan forums for a discussion of that issue.

**Comment by urchgene** [comment]
Thanks @goldingn. I get it now.
