### ISSUE TITLE
Installing greta: "Did not find VS in registry or in VS140COMNTOOLS env var - exiting" Error: Error 1 occurred installing packages into conda environment r-tensorflow

### ISSUE THREAD

**Issue by troelsring** [greta-dev/greta#278]
I had a new R Studio R version 3.5.3  and reinstalled anaconda. So passed install_tensorflow(method = "conda") and it looked well
However: reticulate::conda_install("r-tensorflow", "tensorflow-probability", pip = TRUE) passed an error as mentioned - the entire message was depressing:

> reticulate::conda_install("r-tensorflow", "tensorflow-probability", pip = TRUE)

C:\Users\Troels\Documents>python C:\Users\Troels\ANACON~1\envs\r-tensorflow\etc\keras\load_config.py  1>temp.txt 

C:\Users\Troels\Documents>set /p KERAS_BACKEND= 0<temp.txt 

C:\Users\Troels\Documents>del temp.txt 

C:\Users\Troels\Documents>python -c "import keras"  1>nul 2>&1 

C:\Users\Troels\Documents>if errorlevel 1 (
ver  1>nul  
 set "KERAS_BACKEND=theano"  
 python -c "import keras"  1>nul 2>&1 
) 

C:\Users\Troels\Documents>SET DISTUTILS_USE_SDK=1 

C:\Users\Troels\Documents>SET MSSdk=1 

C:\Users\Troels\Documents>SET platform= 

C:\Users\Troels\Documents>IF /I [AMD64] == [amd64] set "platform=true" 

C:\Users\Troels\Documents>IF /I [] == [amd64] set "platform=true" 

C:\Users\Troels\Documents>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" ) 

C:\Users\Troels\Documents>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /v InstallDir') do SET "VSINSTALLDIR=%B" 
ERROR: The system was unable to find the specified registry key or value.

C:\Users\Troels\Documents>if "" == "" (set "VSINSTALLDIR=" ) 

C:\Users\Troels\Documents>if "" == "" (
ECHO "Did not find VS in registry or in VS140COMNTOOLS env var - exiting"  
 exit 1 
) 
"Did not find VS in registry or in VS140COMNTOOLS env var - exiting"
Error: Error 1 occurred installing packages into conda environment r-tensorflow

I hope to find out what to do next
Best wishes
Troels

**Comment by Voltemand** [comment]
Hi, 

There might be something useful in these links:

https://github.com/flatironinstitute/CaImAn/issues/418

https://stackoverflow.com/questions/53524031/how-to-deal-with-error-at-activating-environment

Sorry to not be more help!

Best.

**Comment by troelsring** [comment]
Thanks a lot – also found this

 <https://forum.greta-stats.org/t/installing-greta-robust-instructions-as-of-march-31-2019/98> https://forum.greta-stats.org/t/installing-greta-robust-instructions-as-of-march-31-2019/98

 

bw

Troels

 

Fra: Jeffrey Pullin <notifications@github.com> 
Sendt: 19. maj 2019 12:08
Til: greta-dev/greta <greta@noreply.github.com>
Cc: troelsring <tring@gvdnet.dk>; Author <author@noreply.github.com>
Emne: Re: [greta-dev/greta] Installing greta: "Did not find VS in registry or in VS140COMNTOOLS env var - exiting" Error: Error 1 occurred installing packages into conda environment r-tensorflow (#278)

 

Hi,

There might be something useful in these links:

flatironinstitute/CaImAn#418 <https://github.com/flatironinstitute/CaImAn/issues/418> 

https://stackoverflow.com/questions/53524031/how-to-deal-with-error-at-activating-environment

Sorry to not be more help!

Best.

**Comment by goldingn** [comment]
would you mind trying this with the current GitHub release of greta? It's stricter on the versions of TensorFlow, TensorFlow Probability and r tensorflow it depends on, so hopefully will make installation of those dependencies easier.

**Comment by njtierney** [comment]
Hi there @troelsring troelsring ! :wave:

There is a new approach in {greta} to installation, it involves some interactive prompts that arise when you install greta, which help setup a python environment with a specific version of python and other python packages. It should help make everything more reproducible and easier to implement. Are you able to give this a try?

# Install current master branch of greta

```r
# install.packages("remotes")
remotes::install_github("greta-dev/greta")
```

# Restart R

# Load greta with `library(greta)`
```r
library(greta)
```

![image](https://user-images.githubusercontent.com/6488485/124245393-8af44e80-db52-11eb-9083-ecba1390a1fb.png)

# Create a greta model

This will initialise python and trigger internal checks that make sure packages are installed. Something like this code is short and sweet and should trigger this.

```r
model(normal(0,1))
```

![image](https://user-images.githubusercontent.com/6488485/124245709-d27ada80-db52-11eb-902f-b5e7f0c94bd9.png)


Then this:

![image](https://user-images.githubusercontent.com/6488485/124245737-d870bb80-db52-11eb-945c-e7b013656c1e.png)

Follow these instructions:

# Install greta dependencies

```r
install_greta_deps()
```

![image](https://user-images.githubusercontent.com/6488485/124245836-f4745d00-db52-11eb-864c-bf63bfdb14cc.png)

![image](https://user-images.githubusercontent.com/6488485/124245963-11a92b80-db53-11eb-9a56-c1ed87ba296a.png)

![image](https://user-images.githubusercontent.com/6488485/124246257-57fe8a80-db53-11eb-92d2-e132ee108bc1.png)

# Restart R + run `library(greta)`

```r
library(greta)
```

# Create a greta model

```r
model(normal(0,1))
```

![image](https://user-images.githubusercontent.com/6488485/124246524-94ca8180-db53-11eb-9c0b-58bc7a234480.png)

![image](https://user-images.githubusercontent.com/6488485/124246541-998f3580-db53-11eb-8324-0b887ee4d124.png)


Let us know if this works! 😄

**Comment by njtierney** [comment]
I'm going to close this issue as I'm on a bit of an issue clean up 🧹  

Please feel free to reopen if the new installation process hasn't solved this for you!
