### ISSUE TITLE
Gaussian Process in greta

### ISSUE THREAD

**Issue by lionel68** [greta-dev/greta#303]
I am fiddling around with spatial regression models these days following the approach outline here: https://becarioprecario.bitbucket.io/spde-gitbook/ch-intro.html#sec:intro.

I was trying to see how to get this to work with greta and based on the following Stan code: https://mc-stan.org/docs/2_19/stan-users-guide/fit-gp-section.html, I used the following R code:

```
cMatern <- function(h, nu, kappa) {
  intt <- ifelse(h > 0, besselK(h * kappa, nu) * (h * kappa)^nu / 
           (base::gamma(nu) * 2^(nu - 1)), 1) 
  #intt <- intt * sigma
  return(intt)
}

# simulate some data
n <- 200
pts <- cbind(s1 = sample(1:n / n - 0.5 / n)^2,
             s2 = sample(1:n / n - 0.5 / n)^2)
dmat <- as.matrix(dist(pts))

# model parameter 
beta0 <- 10
sigma2e <- 0.3
sigma2u <- 5
kappa <- 7
nu <- 1

mcor <- cMatern(dmat, nu, kappa) 
mcov <- sigma2e * diag(nrow(mcor)) + mcor * sigma2u

R <- chol(mcov)
y1 <- beta0 + drop(crossprod(R, rnorm(n))) 

# greta modelling
## parameters
beta_0 <- normal(0, 1)
sigma_e <- cauchy(0, 5, truncation = c(0, Inf))
sigma_u <- cauchy(0, 5, truncation = c(0, Inf))
kappa <- normal(0, 1)
nu <- normal(0, 1)
eta <- normal(0, 1)

# linear predictor derivation
K <- cMatern(dmat, nu, kappa) 
K <- K * sigma_u
diag(K) <- diag(K) + 1e-9
L_K <- chol(K)
f <- L_K * eta + beta_0
# model
distribution(y1) <- normal(f, sigma_e)
```
And I get the following error: "Error: cannot convert objects with missing or infinite values to greta_arrays".

So my questions:
* are such types of models supported by greta right now?
* if yes how should they be implemented?

Thanks!

**Comment by goldingn** [comment]
Hi @lionel68, this is definitely possible, and I can ping you an example. Since this is a modelling question, would you mind re-posting this on [the forum](https://forum.greta-stats.org/) instead? That way other people can find it and contribute more easily.

**Comment by goldingn** [comment]
moved over [to forum](https://forum.greta-stats.org/t/gaussian-process-in-greta-matern-covariance/151/7) and answered there, thanks!
