### ISSUE TITLE
Release greta 0.3.1

### ISSUE THREAD

**Issue by goldingn** [greta-dev/greta#304]
(checklist adapted from a dplyr release checklist)

Prepare for release:

 - [x] ``devtools::check(env_vars = c(`RELEASE_CANDIDATE` = 'true'))``
 - [x] `devtools::check_win_devel()`
 - [x] `rhub::check_for_cran()`
 - [x] Polish `NEWS`

Submit to CRAN:

 - [x] `usethis::use_version('patch')`
 - [x] Update `cran-comments.md`
 - [x] `devtools::submit_cran()`
 - [x] Approve email

Wait for CRAN...

 - [x] Accepted 🎉
 - [ ] `usethis::use_github_release()`
 - [ ] `usethis::use_dev_version()`
 - [ ] Update JOSS paper version
 - [ ] Tweet

**Comment by jeffreypullin** [comment]
You probably know this @goldingn, but just in case you don't this sort of release issue can be generated with `usethis::use_release_issue()`

**Comment by goldingn** [comment]
@jeffreypullin Aaah, I didn't. I knew there was an RStudio-backed template somewhere but couldn't find it in 10 mins of googling. It was under my nose all along!

**Comment by goldingn** [comment]
Goddamned Travis.
