### ISSUE TITLE
Website not displaying properly

### ISSUE THREAD

**Issue by jeffreypullin** [greta-dev/greta#312]
I just noticed that the greta homepage at https://greta-stats.org/ isn't displaying properly. I see:

![Screen Shot 2019-08-17 at 10 49 59 pm](https://user-images.githubusercontent.com/34267114/63211956-b4b05200-c141-11e9-8c29-f98fd60e3758.png)

**Comment by goldingn** [comment]
Ah shit. I must have rebuilt it with a more recent version of pkgdown, that's ignoring my suppression of the side panel. Will see if I can fix now.

**Comment by goldingn** [comment]
Good catch, it had only been like that for about 15 mins when you caught it!
I've rolled back the website for now and will fix the source code tomorrow.

**Comment by jeffreypullin** [comment]
Sounds good - glad I could help.
