### ISSUE TITLE
tfprobability on CRAN

### ISSUE THREAD

**Issue by skeydan** [greta-dev/greta#319]
Hi @goldingn,

just wanted to let you know that tfprobability is on CRAN now :-)

https://cran.r-project.org/web/packages/tfprobability/index.html

I also wanted to say if ever you were interested to publish a post about greta on our blog
https://blogs.rstudio.com/tensorflow/
we would be very happy to feature it :-)

**Comment by dirmeier** [comment]
In the name of everyone who uses `tf` and `tfp` in R: thank you!!

**Comment by skeydan** [comment]
you're very welcome! :-)

**Comment by goldingn** [comment]
Great news, thanks @skeydan!

I'm planning a dev sprint on greta in January, so migration to tfprobability will probably happen then.
