### ISSUE TITLE
Installation fails with Illegal instruction (core dumped) on Ubuntu

### ISSUE THREAD

**Issue by n-kall** [greta-dev/greta#320]
Installing greta in R 3.6 on Ubuntu 18.04 fails and gives the following traceback (also occurs on Ubuntu 19.10):

```r
> install.packages("greta")
Installing package into ‘/home/username/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/greta_0.3.1.tar.gz'
Content type 'application/x-gzip' length 882526 bytes (861 KB)
==================================================
downloaded 861 KB

* installing *source* package ‘greta’ ...
** package ‘greta’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location

 *** caught illegal operation ***
address 0x7fc3e270765f, cause 'illegal operand'

Traceback:
 1: py_module_import(module, convert = convert)
 2: import(module)
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch({    import(module)    TRUE}, error = clear_error_handler(FALSE))
 7: reticulate::py_module_available("tensorflow")
 8: have_tf()
 9: check_tf_version("startup")
10: fun(libname, pkgname)
11: doTryCatch(return(expr), name, parentenv, handler)
12: tryCatchOne(expr, names, parentenv, handlers[[1L]])
13: tryCatchList(expr, classes, parentenv, handlers)
14: tryCatch(fun(libname, pkgname), error = identity)
15: runHook(".onLoad", env, package.lib, package)
16: loadNamespace(package, lib.loc)
17: doTryCatch(return(expr), name, parentenv, handler)
18: tryCatchOne(expr, names, parentenv, handlers[[1L]])
19: tryCatchList(expr, classes, parentenv, handlers)
20: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
21: library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE)
22: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
23: suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE))
24: doTryCatch(return(expr), name, parentenv, handler)
25: tryCatchOne(expr, names, parentenv, handlers[[1L]])
26: tryCatchList(expr, classes, parentenv, handlers)
27: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
28: try(suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE)))
29: tools:::.test_load_package("greta", "/home/username/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-greta/00new")
An irrecoverable exception occurred. R is aborting now ...
Illegal instruction (core dumped)
ERROR: loading failed
* removing ‘/home/username/R/x86_64-pc-linux-gnu-library/3.6/greta’
Warning in install.packages :
  installation of package ‘greta’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpkHutkb/downloaded_packages’

```

**Comment by goldingn** [comment]
Ooh, interesting!

Looks like there's some issue with reticulate finding python (and python modules).

My guess is that you'll get a very similar error doing things with reticulate. E.g.:
```r
library(reticulate)
py_module_available("tensorflow")
```

I suspect there's something amiss with your python installation (at least the one that reticulate is looking at), since you shouldn't get an illegal operation error just form tensorflow not being available. If you can replicate with the reticulate code alone, you might get more insightful help [over here](https://github.com/rstudio/reticulate/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). But I'm happy to help if I can.

**Comment by njtierney** [comment]
Hi there, are you able to confirm if this error is still happening with the new version of greta?

There is a new approach in {greta} to installation, it involves some interactive prompts that arise when you install greta, which help setup a python environment with a specific version of python and other python packages. It should help make everything more reproducible and easier to implement. 

Let us know if you run into any issues and we will try and resolve as soon as possible.

# Install current master branch of greta

```r
# install.packages("remotes")
remotes::install_github("greta-dev/greta")
```

# Restart R

# Load greta with `library(greta)`
```r
library(greta)
```

![image](https://user-images.githubusercontent.com/6488485/124245393-8af44e80-db52-11eb-9083-ecba1390a1fb.png)

# Create a greta model

This will initialise python and trigger internal checks that make sure packages are installed. Something like this code is short and sweet and should trigger this.

```r
model(normal(0,1))
```

![image](https://user-images.githubusercontent.com/6488485/124245709-d27ada80-db52-11eb-902f-b5e7f0c94bd9.png)


Then this:

![image](https://user-images.githubusercontent.com/6488485/124245737-d870bb80-db52-11eb-945c-e7b013656c1e.png)

Follow these instructions:

# Install greta dependencies

```r
install_greta_deps()
```

![image](https://user-images.githubusercontent.com/6488485/124245836-f4745d00-db52-11eb-864c-bf63bfdb14cc.png)

![image](https://user-images.githubusercontent.com/6488485/124245963-11a92b80-db53-11eb-9a56-c1ed87ba296a.png)

![image](https://user-images.githubusercontent.com/6488485/124246257-57fe8a80-db53-11eb-92d2-e132ee108bc1.png)

# Restart R + run `library(greta)`

```r
library(greta)
```

# Create a greta model

```r
model(normal(0,1))
```

![image](https://user-images.githubusercontent.com/6488485/124246524-94ca8180-db53-11eb-9c0b-58bc7a234480.png)

![image](https://user-images.githubusercontent.com/6488485/124246541-998f3580-db53-11eb-8324-0b887ee4d124.png)


Let us know if this works! 😄
