### ISSUE TITLE
joint uniform distribution

### ISSUE THREAD

**Issue by rogiersbart** [greta-dev/greta#337]
It seems something's going wrong with joint uniform distributions at the moment. Would have asked on the forum first, but that seems to be down at the moment. Also, in the joint distribution tests it seems the uniform one is not there, so here's a reprex trying to illustrate something might be wrong: Comparing the Mean and SD columns with the uniform and normal function arguments below seems to suggest in the first case draws are out of bounds, while for the second it seems as expected ...

``` r
library("greta")
#> 
#> Attaching package: 'greta'
#> The following objects are masked from 'package:stats':
#> 
#>     binomial, cov2cor, poisson
#> The following objects are masked from 'package:base':
#> 
#>     %*%, apply, backsolve, beta, chol2inv, colMeans, colSums, diag,
#>     eigen, forwardsolve, gamma, identity, rowMeans, rowSums, sweep,
#>     tapply
library("magrittr")
joint(uniform(0, 1), uniform(1, 2)) %>%
  model() %>%
  mcmc(warmup = 0, chains = 10, verbose = FALSE) %>%
  summary()
#> 
#> Iterations = 1:1000
#> Thinning interval = 1 
#> Number of chains = 10 
#> Sample size per chain = 1000 
#> 
#> 1. Empirical mean and standard deviation for each variable,
#>    plus standard error of the mean:
#> 
#>          Mean    SD Naive SE Time-series SE
#> .[1,1] -3.027 10.93   0.1093          1.195
#> .[1,2] -2.212 13.54   0.1354          1.882
#> 
#> 2. Quantiles for each variable:
#> 
#>          2.5%    25%    50%   75% 97.5%
#> .[1,1] -24.30 -10.46 -3.766 4.841 19.71
#> .[1,2] -24.75 -11.32 -1.926 5.354 35.74
joint(normal(0, 1), normal(0, 2)) %>%
  model() %>%
  mcmc(warmup = 0, chains = 10, verbose = FALSE) %>%
  summary()
#> 
#> Iterations = 1:1000
#> Thinning interval = 1 
#> Number of chains = 10 
#> Sample size per chain = 1000 
#> 
#> 1. Empirical mean and standard deviation for each variable,
#>    plus standard error of the mean:
#> 
#>            Mean     SD Naive SE Time-series SE
#> .[1,1] -0.03289 0.9834 0.009834        0.04508
#> .[1,2] -0.20528 1.9741 0.019741        0.17572
#> 
#> 2. Quantiles for each variable:
#> 
#>          2.5%     25%      50%    75% 97.5%
#> .[1,1] -1.918 -0.7288 -0.03006 0.6441 1.893
#> .[1,2] -4.176 -1.4958 -0.23969 1.0750 3.694
sessionInfo()
#> R version 3.6.2 (2019-12-12)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17763)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=Dutch_Belgium.1252  LC_CTYPE=Dutch_Belgium.1252   
#> [3] LC_MONETARY=Dutch_Belgium.1252 LC_NUMERIC=C                  
#> [5] LC_TIME=Dutch_Belgium.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] magrittr_1.5 greta_0.3.1 
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.3        compiler_3.6.2    pillar_1.4.3      highr_0.8        
#>  [5] base64enc_0.1-3   prettyunits_1.1.0 tools_3.6.2       progress_1.2.2   
#>  [9] zeallot_0.1.0     digest_0.6.23     jsonlite_1.6      evaluate_0.14    
#> [13] tibble_2.1.3      lattice_0.20-38   pkgconfig_2.0.3   rlang_0.4.2      
#> [17] yaml_2.2.0        parallel_3.6.2    xfun_0.12         coda_0.19-3      
#> [21] stringr_1.4.0     knitr_1.27        rappdirs_0.3.1    vctrs_0.2.1      
#> [25] globals_0.12.5    hms_0.5.3         grid_3.6.2        reticulate_1.14  
#> [29] listenv_0.8.0     R6_2.4.1          rmarkdown_2.1     whisker_0.4      
#> [33] backports_1.1.5   codetools_0.2-16  htmltools_0.4.0   tfruns_1.4       
#> [37] future_1.16.0     tensorflow_2.0.0  stringi_1.4.5     crayon_1.3.4
```

<sup>Created on 2020-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by goldingn** [comment]
Thanks for the bug report and the clear reprex!

I can replicate it, and it's the same in the current dev version. It also seems to apply to truncated distributions - in both cases the bounds are ignored:
```r
x <- joint(normal(0, 2, truncation = c(-3, -2)),
           normal(0, 1, truncation = c(-3, -2)))
m <- model(x)
draws <- mcmc(m)
summary(draws)$quantiles
```
> ```
>            2.5%        25%          50%       75%    97.5%
> [1,1] -3.894055 -1.4365784 -0.009147919 1.4242193 3.886617
> [1,2] -1.980323 -0.6800545 -0.005714715 0.6586376 1.938162
> ```

but the bounds of other distributions with naturally restricted support seem fine:

```r
x <- joint(lognormal(0, 1),
           beta(3, 1))
m <- model(x)
draws <- mcmc(m)
summary(draws)$quantiles
```
> ```
>            2.5%       25%       50%       75%     97.5%
> [1,1] 0.1456290 0.5104220 1.0643067 2.0676793 5.8564399
> [1,2] 0.2875137 0.6291034 0.7908078 0.9063772 0.9907832
> ```

I'll add tests for this and get on to a fix now.

---

Thanks also for flagging that the greta forum was down. Apparently the automatic update I did last week went awry and I hadn't noticed. That's up now. Though GitHub issues is the best place for bug reports like this anyway.

**Comment by rogiersbart** [comment]
That's great Nick! And thanks for the awesome package. Looking forward to the new features you are working on!

**Comment by goldingn** [comment]
Progress on this over in #338 - this turned out to be a bit of a can of worms :)
It was a good motivation to switch over to using more features from tensorflow probability though, and fix up a couple of other things that have been bothering me.

The example above works in that new branch. Now just trying to finish off a tricky edge case and a new bug that's popped up!

**Comment by rogiersbart** [comment]
Thanks for so quickly looking into this Nick!
