### ISSUE TITLE
greta::model captures NSE arguments

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [greta-dev/greta#343]
I frequently pass `NSE` arguments (e.g. `name`s) to use them with tidyevaluation. However, call to `greta::model` tries to capture everything in the current environment, including the "values", to which `NSE` `name`s/`sym`bols point to (i.e. to *nowhere*). This results in the following error.
``` r
# Activating tensorflow environment
reticulate::use_condaenv("r-tensorflow-gpu", required = TRUE)

# Disabling GPU to speed up initialization
Sys.setenv("CUDA_VISIBLE_DEVICES" = -1)

f <- function(x = hp) { # NSE argument
    y <- greta::normal(1, 2)
    mdl <- greta::model(y)
}

f()
#> Error in FUN(X[[i]], ...): object 'hp' not found

packageDescription("greta")[c("Version", "RemoteSha")]
#> $Version
#> [1] "0.3.1.9010"
#> 
#> $RemoteSha
#> [1] "d26b991d238b4e43d0f021c035585f7fd757cbf5"
```

<sup>Created on 2020-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by goldingn** [comment]
Thanks for the report. I'll take a look and see if I can find a fix that maintains the current behaviour

**Comment by goldingn** [comment]
I just pushed a fix for this specific behaviour, but if you find any other rough edges with metaprogramming like this, please let me know!

**Comment by Ilia-Kosenkov** [comment]
@goldingn Thank you for fixing it! I will update to the latest dev version and see if similar issues appear.
