### ISSUE TITLE
Problem installing jupyter in conda environment 

### ISSUE THREAD

**Issue by LisaTUWien** [greta-dev/greta#353]
Hello,
after researching a lot I still couldn't find an answer what the solution to my problem might be. I try to install jupyter notebook in an environment, but it always ends in an error.
That error also occurs when trying to install cerain libaries, such as earthpy.

The exact error message is following:

(earth-analytics-python) C:\Users\riede\earth-analytics\earth-analytics-python-env>conda install jupyter
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\riede\miniconda3\envs\earth-analytics-python

  added / updated specs:
    - jupyter

The following NEW packages will be INSTALLED:

  backcall           conda-forge/noarch::backcall-0.1.0-py_0
  bleach             conda-forge/noarch::bleach-3.1.5-pyh9f0ad1d_0
  colorama           conda-forge/noarch::colorama-0.4.3-py_0
  decorator          conda-forge/noarch::decorator-4.4.2-py_0
  defusedxml         conda-forge/noarch::defusedxml-0.6.0-py_0
  entrypoints        conda-forge/win-64::entrypoints-0.3-py37hc8dfbb8_1001
  importlib-metadata conda-forge/win-64::importlib-metadata-1.6.0-py37hc8dfbb8_0
  importlib_metadata conda-forge/noarch::importlib_metadata-1.6.0-0
  ipykernel          conda-forge/win-64::ipykernel-5.3.0-py37h5ca1d4c_0
  ipython            conda-forge/win-64::ipython-7.14.0-py37hc8dfbb8_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  ipywidgets         conda-forge/noarch::ipywidgets-7.5.1-py_0
  jedi               conda-forge/win-64::jedi-0.17.0-py37hc8dfbb8_0
  jinja2             conda-forge/noarch::jinja2-2.11.2-pyh9f0ad1d_0
  jsonschema         conda-forge/win-64::jsonschema-3.2.0-py37hc8dfbb8_1
  jupyter            conda-forge/noarch::jupyter-1.0.0-py_2
  jupyter_client     conda-forge/noarch::jupyter_client-6.1.3-py_0
  jupyter_console    conda-forge/noarch::jupyter_console-6.1.0-py_1
  jupyter_core       conda-forge/win-64::jupyter_core-4.6.3-py37hc8dfbb8_1
  libclang           conda-forge/win-64::libclang-9.0.1-default_hf44288c_0
  libsodium          conda-forge/win-64::libsodium-1.0.17-h2fa13f4_0
  markupsafe         conda-forge/win-64::markupsafe-1.1.1-py37h8055547_1
  mistune            conda-forge/win-64::mistune-0.8.4-py37h8055547_1001
  nbconvert          conda-forge/win-64::nbconvert-5.6.1-py37hc8dfbb8_1
  nbformat           conda-forge/noarch::nbformat-5.0.6-py_0
  notebook           conda-forge/win-64::notebook-6.0.3-py37hc8dfbb8_0
  packaging          conda-forge/noarch::packaging-20.4-pyh9f0ad1d_0
  pandoc             conda-forge/win-64::pandoc-2.9.2.1-0
  pandocfilters      conda-forge/noarch::pandocfilters-1.4.2-py_1
  parso              conda-forge/noarch::parso-0.7.0-pyh9f0ad1d_0
  pickleshare        conda-forge/win-64::pickleshare-0.7.5-py37hc8dfbb8_1001
  prometheus_client  conda-forge/noarch::prometheus_client-0.8.0-pyh9f0ad1d_0
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.5-py_0
  prompt_toolkit     conda-forge/noarch::prompt_toolkit-3.0.5-0
  pygments           conda-forge/noarch::pygments-2.6.1-py_0
  pyqt               conda-forge/win-64::pyqt-5.12.3-py37h1834ac0_3
  pyrsistent         conda-forge/win-64::pyrsistent-0.16.0-py37h8055547_0
  pywin32            conda-forge/win-64::pywin32-227-py37hfa6e2cd_0
  pywinpty           conda-forge/win-64::pywinpty-0.5.7-py37_0
  pyzmq              conda-forge/win-64::pyzmq-19.0.1-py37h453f00a_0
  qt                 conda-forge/win-64::qt-5.12.5-h7ef1ec2_0
  qtconsole          conda-forge/noarch::qtconsole-4.7.4-pyh9f0ad1d_0
  qtpy               conda-forge/noarch::qtpy-1.9.0-py_0
  send2trash         conda-forge/noarch::send2trash-1.5.0-py_0
  terminado          conda-forge/win-64::terminado-0.8.3-py37hc8dfbb8_1
  testpath           conda-forge/noarch::testpath-0.4.4-py_0
  traitlets          conda-forge/win-64::traitlets-4.3.3-py37hc8dfbb8_1
  wcwidth            conda-forge/noarch::wcwidth-0.1.9-pyh9f0ad1d_0
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  widgetsnbextension conda-forge/win-64::widgetsnbextension-3.5.1-py37_0
  winpty             conda-forge/win-64::winpty-0.4.3-4
  zeromq             conda-forge/win-64::zeromq-4.3.2-h6538335_2
  zipp               conda-forge/noarch::zipp-3.1.0-py_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: - b'Enabling notebook extension jupyter-js-widgets/extension...\n      - Validating: ok\n'
done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'conda-forge::qt-5.12.5-h7ef1ec2_0'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::qt-5.12.5-h7ef1ec2_0
location of failed script: C:\Users\riede\miniconda3\envs\earth-analytics-python\Scripts\.qt-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:         1 Datei(en) kopiert.

stderr: Der Befehl "chcp" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "chcp" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "chcp" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

return code: 1

()

I would be more than greatful for any suggestions on how I can solve that issue!

**Comment by njtierney** [comment]
Hi there! :wave:

There is a new approach in {greta} to installation, it involves some interactive prompts that arise when you install greta, which help setup a python environment with a specific version of python and other python packages. It should help make everything more reproducible and easier to implement. Are you able to give this a try?

# Install current master branch of greta

```r
# install.packages("remotes")
remotes::install_github("greta-dev/greta")
```

# Restart R

# Load greta with `library(greta)`
```r
library(greta)
```

![image](https://user-images.githubusercontent.com/6488485/124245393-8af44e80-db52-11eb-9083-ecba1390a1fb.png)

# Create a greta model

This will initialise python and trigger internal checks that make sure packages are installed. Something like this code is short and sweet and should trigger this.

```r
model(normal(0,1))
```

![image](https://user-images.githubusercontent.com/6488485/124245709-d27ada80-db52-11eb-902f-b5e7f0c94bd9.png)


Then this:

![image](https://user-images.githubusercontent.com/6488485/124245737-d870bb80-db52-11eb-945c-e7b013656c1e.png)

Follow these instructions:

# Install greta dependencies

```r
install_greta_deps()
```

![image](https://user-images.githubusercontent.com/6488485/124245836-f4745d00-db52-11eb-864c-bf63bfdb14cc.png)

![image](https://user-images.githubusercontent.com/6488485/124245963-11a92b80-db53-11eb-9a56-c1ed87ba296a.png)

![image](https://user-images.githubusercontent.com/6488485/124246257-57fe8a80-db53-11eb-92d2-e132ee108bc1.png)

# Restart R + run `library(greta)`

```r
library(greta)
```

# Create a greta model

```r
model(normal(0,1))
```

![image](https://user-images.githubusercontent.com/6488485/124246524-94ca8180-db53-11eb-9c0b-58bc7a234480.png)

![image](https://user-images.githubusercontent.com/6488485/124246541-998f3580-db53-11eb-8324-0b887ee4d124.png)


Let us know if this works! 😄

**Comment by njtierney** [comment]
We have written up the new installation instructions here: https://greta-stats.org/articles/faq.html#how-do-i-install-greta-dependencies
