### ISSUE TITLE
Transition travis/appveyor over to github actions

### ISSUE THREAD

**Issue by njtierney** [greta-dev/greta#362]
See #332

**Comment by njtierney** [comment]
read up on setting environmnent objects etc here 

https://docs.github.com/en/actions/reference/environment-variables

also need to set up

- [ ] installing R binary pkgs
- [ ] R pkgs
- [ ] cache pip
- [ ] pkgs to install on linux
- [ ] steps to perform before install (although perhaps with new changes to installation with reticulate this could be ommitted?)
- [ ] when to email?

**Comment by njtierney** [comment]
I think that the env objects defined in the [travis yaml](https://github.com/greta-dev/greta/blob/master/.travis.yml#L5) can be replaced with the very similar [GH actions env](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#env).

These environment variables are used to determine [when to trigger certain tests](https://github.com/greta-dev/greta/blob/92dd0ffaeb2d643ca0f1701ddda7cdb2be87f8eb/tests/testthat/helpers.R#L731) - how are these typically set to TRUE/FALSE, @goldingn ?

I wonder if we we might also be able to trigger certain environments by adding a tag to a github branch, e.g.

https://docs.github.com/en/actions/reference/environment-variables

Or if it just might be simplest to set the environment variable manually in the text file when we want certain tests to run?

**Comment by goldingn** [comment]
They're currently set by manually changing the yaml. Tags on a branch sound like a much better idea!

**Comment by njtierney** [comment]
OK cool - it might end up being a touch more complicated, I'll see how we go and we might be able to rig up something fancy later, but manually change it in the interim.
