### ISSUE TITLE
Implement "branchmarking" - benchmarking for PRs in greta

### ISSUE THREAD

**Issue by njtierney** [greta-dev/greta#365]
The [touchstone](https://github.com/lorenzwalthert/touchstone) package is still under development, but looks like it provides a simple workflow for comparing speed of different branches.

It looks like STAN has an approach for this, see in [this PR](https://github.com/stan-dev/stan/pull/3033), which is done by [this buildbot](https://github.com/stan-buildbot?tab=overview&from=2021-02-01&to=2021-02-28), or perhaps [here](https://github.com/stan-dev/performance-tests-cmdstan). 

It seems like the touchstone approach might be a bit simpler to implement.

**Comment by njtierney** [comment]
Example script here: https://github.com/r-lib/styler/blob/master/touchstone/script.R

**Comment by njtierney** [comment]
Example to test out - https://github.com/greta-dev/greta/issues/309

**Comment by njtierney** [comment]
It appears that `touchstone` is now ready to use, it would be pretty easy to add to `greta` now:

https://github.com/lorenzwalthert/touchstone

**Comment by lorenzwalthert** [comment]
👍 @njtierney. Let me know if you have questions for touchstone. There were major documentation and feature and API updates since April and we are planning on submitting to CRAN soon.

**Comment by assignUser** [comment]
Hey @njtierney {touchstone} has matured a lot and we are getting ready to submit to rOpenSci and CRAN. 
Now is a good time to test it, we would love some feedback from new users!

**Comment by lorenzwalthert** [comment]
We can also provide some guidance if you need help in implementing the bench marls you want to run. With thei [GitHub Search](https://github.com/search?q=path%3A.github%2Fworkflows+filename%3Atouchstone-receive.yaml&type=Code), you can find repos that are already using {touchstone} and how they are using it.

**Comment by njtierney** [comment]
Hey @lorenzwalthert and @assignUser !

Amazing! This looks really great, I've got a few more things that I want to deal with in greta, but this would be really interesting for when we are upgrading to tensorflow 2.0.0 to see if we get much of a speedup within greta. I'll move this to the next milestone after the upcoming release, it will be really fun to see how speed changes with greta!

**Comment by njtierney** [comment]
First attempt at this is here: https://github.com/greta-dev/greta/issues/365

Just thought I'd try and implement this before we really get going with the upgrade to TF2, so we can see if there are any interesting speed ups!
