### ISSUE TITLE
review uses of vapply and refactor where duplicated

### ISSUE THREAD

**Issue by njtierney** [greta-dev/greta#377]
e.g., 

https://github.com/greta-dev/greta/blob/master/R/simulate.R#L65

```
target_node_names <- vapply(target_nodes,
    member,
    "unique_name",
    FUN.VALUE = character(1)
  )
  object_node_names <- vapply(object$dag$node_list,
    member,
    "unique_name",
    FUN.VALUE = character(1)
  )
```

and 
```
https://github.com/greta-dev/greta/blob/master/R/utils.R#L504
```

can be replaced with the new base::lengths

**Comment by njtierney** [comment]
In vapply, FUN.VALUE is sometimes “” and other times, character(1), is there a difference/benefit from doing this?

**Comment by goldingn** [comment]
Same result, but I think I switched to `character(1)` as it makes the intent clearer

**Comment by njtierney** [comment]
Some common vapply patterns:

- `vapply(nodes, dag$tf_name, ...)`
- `vapply(x, is.null, ...)` 
- `vapply(x, has_distribution, ...)`
- `vapply(x, identical, ...)`
- `vapply(x, is.greta_array)`
- `vapply(parents/children, member, "unique_name", ...)`
- `vapply(dot_nodes, is_scalar, logical(1))`
- `vapply(names, deparse, "")`
- `classes <- vapply(x, class, "")`
