### ISSUE TITLE
Improve message handling when installing + initialising python.

### ISSUE THREAD

**Issue by njtierney** [greta-dev/greta#421]
Related to #417 but wanted to separate the issues out so I could merge that branch earlier

- [x] Can we work out at which stage Python is initialised, as this may mean we can ignore needing to restart (not critical) (so can we not initialise python when checking if python is installed etc - can we have a message that pops up here?)
- [x] Capture conda installation text and suppress during installation 
- [x] Replace conda installation test with our own shorter messages on progress
- [x] Make conda installation text available to the user on completion if needed (with a "run `installation_messages()` to get all outputs for debugging purposes" note).

**Comment by njtierney** [comment]
> Can we work out at which stage Python is initialised, as this may mean we can ignore needing to restart (not critical) (so can we not initialise python when checking if python is installed etc - can we have a message that pops up here?)

@goldingn I think this is covered in #422 ?

**Comment by goldingn** [comment]
Yeah, I don't think it's possible to check all of these things without initialising python. We could check whether there is a python installation without initialisation by switching to `reticulate::py_discover_config()`, but we'll need to initialise to look for the other packages anyway (reticulate checks for them by trying to import them and then catching any errors).

So yes, we need to initialise (#422 does the message) and user will need to restart after installing the dependencies.
