### ISSUE TITLE
Document new installation process and add FAQ to website

### ISSUE THREAD

**Issue by njtierney** [greta-dev/greta#424]
(Requires fixing the current website build (#363))

There is a nice new installation interface that guides the user a through installing miniconda and python dependencies. This would be great to document and install on the website, and to add an FAQ to provide some workarounds

e.g.,

- provide the code that `install_greta_deps()` has inside of it in the FAQ, in case people are having issues with greta installation.

**Comment by flyaflya** [comment]
Hi Nick:  Any idea on release date for new install process?  Just trying to plan my own greta-related work and avoid recording an install video for my students if we might see a changes/release soon.    Happy to help test when ready.  Thanks!!

**Comment by njtierney** [comment]
Hi Adam!

I can't give you a hard date at the moment, but, Ideally, I'd like to get a soft release out for greta by the end of September, so we'll have a couple of weeks for people to try it out and get back to us.

When does your course start?

**Comment by flyaflya** [comment]
Late September would be great.  My next course with `greta` will start mid-October.  Thx!!

**Comment by njtierney** [comment]
Hi Adam,

OK great - I'll try and update you as time goes on so if it's looking like we'll be delayed I can keep you in the loop and not disrupt your teaching :)

As an upper bound, we are teaching a greta course in mid November, so I expect we'll be seeing even more work done on {greta} by then.

**Comment by flyaflya** [comment]
Installation of greta still goes smooth for most of my classes.  I could use advice on one issue if you have any.  New Macs with the M1 chip do not seem to play nice with greta.  Python is unfindable by greta even though the Python environment seems to be setup correctly.  Have you discovered this and any workarounds? Seems the reticulate folks are aware of this:  https://github.com/rstudio/reticulate/issues?q=is%3Aissue+is%3Aopen+M1

**Comment by njtierney** [comment]
Hi @flyaflya  - thanks so much for the feedback, glad to hear that greta is going well in your classes, and my apologies for not being in touch sooner.

I have an M1 mac at work, but have been running into other IT issues - getting it to work on M1 architecture is definitely a priority in the future, I'll make a separate issue to note this.

I'm really glad to hear that greta installation largely goes smoothly, I hope we can get the M1 issues rectified soon.
