### ISSUE TITLE
Accomodate breaking changes in R pkg {tensorflow} v2.7

### ISSUE THREAD

**Issue by flyaflya** [greta-dev/greta#459]
By default, `greta`'s guided installation will use the latest release of R's `tensorflow` package (released Nov 9).  Using this latest release of the `tensorflow` package though leads to the following error:

![image](https://user-images.githubusercontent.com/17184441/141341690-698ba237-a779-4f84-bf14-e5062ea93e34.png)

The only remedy to this error that I know is the following two lines to downgrade the `tensorflow` package:
```
install.packages("remotes")
remotes::install_version("tensorflow", version = "2.6.0", repos = "http://cran.us.r-project.org")
```

I believe - could be wrong - the root cause is not a bug, but rather known breaking change:

![image](https://user-images.githubusercontent.com/17184441/141341472-2c426a1d-3bb1-4d6e-9dc9-e2a8c5e87d74.png)
(source: https://github.com/rstudio/tensorflow/releases)

**Comment by njtierney** [comment]
Thanks for posting this, Adam, I'll look into this right away. Hopefully we can make some changes internally to fix this, as trying to install specific R package versions is usually challenging and not allowed.

**Comment by njtierney** [comment]
Just an update - we are running a course this week so I'll get onto this after Wednesday.

**Comment by njtierney** [comment]
Initial debugging ...

```r
# remotes::install_version(package = "tensorflow", version = "2.6.0")
library(greta)
devtools::load_all()
debugonce(skip_dim)
model(normal(0,1))

# 2.7.0 behaviour:
  # changes
  # inside `skip_dim` function, `dim(x)` returns `integer(0)`

# cannot currently confirm the behaviour with 2.6.0 as it does not trigger
# the function, `skim_dim` when debugging...
```

It seems that the `dim` call on a tensorflow object is part of the issue here:

https://github.com/greta-dev/greta/blob/112a96804170d7cccdb76b1f413cdbbb23f0738d/R/tf_functions.R#L63

The error is in:

```r
n_dim <- length(dim(x))
reduction_dims <- seq_len(n_dim - 1)
```

since `dim(x)` returns `integer(0)`, which has length 0... then, `seq_len(0 - 1)` gives an error since this is a negative number, which errors.

Debugging this is tricky as I cannot get the functions `skip_dim` or `tf_sum` to be triggered when running `normal(0,1)`

more digging required!

**Comment by njtierney** [comment]
I believe this is now resolved, @flyaflya 

Thank you again for posting this!

I will start the process of submitting to CRAN today, not sure if I will have enough time to do all of the checks and iron out all the kinks, but you are very welcome to test the new changes now on master :)

**Comment by flyaflya** [comment]
I look forward to testing this out!  I am thrilled to see a new CRAN submission.  Thanks!!!

**Comment by njtierney** [comment]
@flyaflya - I nearly got the CRAN submission done, but we want to try and sort out some issues we noticed on the GH actions for windows, and I'm away on leave this week, so the CRAN submission will happen in the second week of December, just to keep you in the loop!
