### ISSUE TITLE
Error in install_tensorflow(conda = "C:/Users/Chief/AppData/Local/r-miniconda",  :    You should call install_keras() only in a fresh R session that has not yet initialized Keras and TensorFlow (this is to avoid DLL in use errors during installation)

### ISSUE THREAD

**Issue by noahmthomas-nmt** [greta-dev/greta#477]
Hi,

I tried running the set here: https://greta-stats.org/articles/get_started.html.

I was unable to find the function `install_greta_deps()` and instead used the "Standard installation" workaround but I was unable to force python_version 3.7.

Then using `install_tensorflow()`,  I got an error: 
"Error in install_tensorflow(method = "conda", version = "1.14.0", extra_packages = "tensorflow-probability") : 
  You should call install_keras() only in a fresh R session that has not yet initialized Keras and TensorFlow (this is to avoid DLL in use errors during installation)."

Any help with the installation would be appreciated. 
Let me know what additional information is needed.

**Comment by njtierney** [comment]
Hi there @noahmthomas-nmt 

Thanks for posting!

The "get started" vignette should be a bit clearer that you need the development version of `greta`, which is version 0.4.0. I'll update the "get started" vignette to make that clearer.

If the function `install_greta_deps()` is not available, it most likely means that the version of `greta` is not version 0.4.0

Can you tell me the following:

- What version of `greta` are you using? `packageVersion("greta")` should give you the version number

You should hopefully be able to get the `install_greta_deps()` function by running the following:

```r
install.packages("remotes")
remotes::install_github("greta-dev/greta")
```

Let me know how you go, and thanks again for posting your question!

**Comment by njtierney** [comment]
Hi @noahmthomas-nmt!

I'm going to close this issue for the moment, but feel free to open it if you have any further questions/concerns or need help resolving this!  :)

Thanks again for posting.
