### ISSUE TITLE
feedback on install process

### ISSUE THREAD

**Issue by jodeleeuw** [greta-dev/greta#82]
Just wanted to leave a quick note with some feedback on the installation process that could be used to make the documentation clearer.

It took us a while to realize that greta would only run on 64 bit R because tensorflow requires 64 bit python. It seems obvious in hindsight. Because we had both 32 and 64 bit R installed on our machine, `install_github` was trying to install greta for both. It would fail at the 32 bit install, and then not attempt the 64. We fixed this with:

```R
library(devtools)
options(devtools.install.args = "--no-multiarch") 
```

**Comment by goldingn** [comment]
Thanks so much for taking the time to leave this feedback!

That's good to know - I hadn't considered 32 bit machines at all. I'll take a look at whether this has been discussed on the tensorflow R package page yet. If not I'll flag this there too.
