### ISSUE TITLE
add mixture distribution 

### ISSUE THREAD

**Issue by goldingn** [greta-dev/greta#84]
This should have syntax like:
```r
theta = variable(lower = 0, upper = 1, dim = 3)
dist = mixture(normal(0, 1), normal(1, 1), normal (2, 2), weights = theta)
distribution(y) = dist
```
This should strip the distributions from the variables passed to it and define the children of those distributions. Use log_sum_exp to sum the weighted densities on the probability scale. Possibly just let them define themselves in TF, combine the densities into the mixture density, then delete the component TF densities (so they don't count toward the total).

Also add variables representing ordered vectors and simplices (with appropriate jacobians) for use in these models.

**Comment by goldingn** [comment]
This is now implemented in the dev branch, and can be installed with:
```r
devtools::install_github("greta-dev/greta@dev")
```

**Comment by goldingn** [comment]
vectorised mixtures are implemented on the dev branch now, with an example in the doc

**Comment by melondonkey** [comment]
Is this still in the code?  I could not find the source code for mixture() when I tried a search of the repo

**Comment by goldingn** [comment]
it's in the development branch, which you can install with `devtools::install_github("greta-dev/greta@dev")`. I'm *really* close to a CRAN release for the dev branch, so it should be available everywhere soon.
